type CurrencyInfo = {
  [key: string]: {
    countryCode: string
    currencyName: string
  }
}

export const currencyInfo: CurrencyInfo = {
  ISK: { countryCode: "is", currencyName: "Icelandic Krona" },
  GEL: { countryCode: "ge", currencyName: "Georgian Lari" },
  GBP: { countryCode: "gb", currencyName: "British Pound Sterling" },
  BAM: { countryCode: "ba", currencyName: "Bosnia-Herzegovina Convertible Mark" },
  COP: { countryCode: "co", currencyName: "Colombian Peso" },
  BRL: { countryCode: "br", currencyName: "Brazilian Real" },
  RSD: { countryCode: "rs", currencyName: "Serbian Dinar" },
  HUF: { countryCode: "hu", currencyName: "Hungarian Forint" },
  HNL: { countryCode: "hn", currencyName: "Honduran Lempira" },
  MYR: { countryCode: "my", currencyName: "Malaysian Ringgit" },
  EUR: { countryCode: "eu", currencyName: "Euro" },
  CHF: { countryCode: "ch", currencyName: "Swiss Franc" },
  TJS: { countryCode: "tj", currencyName: "Tajikistani Somoni" },
  BMD: { countryCode: "bm", currencyName: "Bermudian Dollar" },
  KZT: { countryCode: "kz", currencyName: "Kazakhstani Tenge" },
  USD: { countryCode: "us", currencyName: "United States Dollar" },
  DKK: { countryCode: "dk", currencyName: "Danish Krone" },
  PEN: { countryCode: "pe", currencyName: "Peruvian Sol" },
  DOP: { countryCode: "do", currencyName: "Dominican Peso" },
  PYG: { countryCode: "py", currencyName: "Paraguayan Guarani" },
  RON: { countryCode: "ro", currencyName: "Romanian Leu" },
  BWP: { countryCode: "bw", currencyName: "Botswana Pula" },
  UAH: { countryCode: "ua", currencyName: "Ukrainian Hryvnia" },
  MZN: { countryCode: "mz", currencyName: "Mozambican Metical" },
  PLN: { countryCode: "pl", currencyName: "Polish Zloty" },
  ILS: { countryCode: "il", currencyName: "Israeli New Shekel" },
  LKR: { countryCode: "lk", currencyName: "Sri Lankan Rupee" },
  INR: { countryCode: "in", currencyName: "Indian Rupee" },
  KWD: { countryCode: "kw", currencyName: "Kuwaiti Dinar" },
  MXN: { countryCode: "mx", currencyName: "Mexican Peso" },
  THB: { countryCode: "th", currencyName: "Thai Baht" },
  NZD: { countryCode: "nz", currencyName: "New Zealand Dollar" },
  BGN: { countryCode: "bg", currencyName: "Bulgarian Lev" },
  KES: { countryCode: "ke", currencyName: "Kenyan Shilling" },
  UYU: { countryCode: "uy", currencyName: "Uruguayan Peso" },
  NGN: { countryCode: "ng", currencyName: "Nigerian Naira" },
  LAK: { countryCode: "la", currencyName: "Lao Kip" },
  MKD: { countryCode: "mk", currencyName: "Macedonian Denar" },
  SEK: { countryCode: "se", currencyName: "Swedish Krona" },
  HKD: { countryCode: "hk", currencyName: "Hong Kong Dollar" },
  ZAR: { countryCode: "za", currencyName: "South African Rand" },
  GTQ: { countryCode: "gt", currencyName: "Guatemalan Quetzal" },
  MDL: { countryCode: "md", currencyName: "Moldovan Leu" },
  CRC: { countryCode: "cr", currencyName: "Costa Rican Colón" },
  CZK: { countryCode: "cz", currencyName: "Czech Koruna" },
  SGD: { countryCode: "sg", currencyName: "Singapore Dollar" },
}
