import type { Coverage } from "@common/analytics/coverage"

import type { MessageTypes, MessageTypesWithSubscriptions } from "../../types"

type PriMessage = Extract<MessageTypes, `pri(${string})`>
type PriSubscription = Extract<MessageTypesWithSubscriptions, `pri(${string})`>

/** Subscriptions are reads unless listed: one that writes must say what it sends. */
type MessageCoverage = { readonly [M in Exclude<PriMessage, PriSubscription>]: Coverage } & {
  readonly [M in PriSubscription]?: Exclude<Coverage, "read">
}

export const MESSAGE_COVERAGE = {
  "pri(accounts.add.external)": {
    event: [
      "account_watch_added",
      "ledger_accounts_imported",
      "external_accounts_imported",
      "contact_added",
    ],
  },
  "pri(accounts.add.derive)": { event: "account_created" },
  "pri(accounts.add.keypair)": { event: "account_created" },
  "pri(accounts.create.json)": { event: "account_created" },
  "pri(accounts.forget)": { event: "account_removed" },
  "pri(accounts.export)": { event: "account_exported" },
  "pri(accounts.export.all)": { event: "account_exported" },
  "pri(accounts.export.pk)": { event: "account_exported" },
  "pri(accounts.rename)": { event: "item_renamed" },
  "pri(accounts.update.contact)": { exempt: "pending 5e" },
  "pri(accounts.external.setIsPortfolio)": { event: "watched_account_portfolio_toggled" },
  "pri(accounts.catalog.runActions)": {
    event: ["folder_created", "folder_deleted", "item_renamed", "account_moved"],
  },
  "pri(accounts.address.lookup)": "read",
  "pri(accounts.derivationPath.next)": "read",
  "pri(accounts.onChainIds.resolveNames)": "read",
  "pri(accounts.onChainIds.lookupAddresses)": "read",
  "pri(accountProxies.refresh)": "read",
  "pri(accountProxies.loadDetails)": "read",
  "pri(accountProxies.updatePalletCache)": "read",
  "pri(analytics.track)": { exempt: "transport" },
  "pri(analytics.requestRisk)": { event: "dapp_request_resolved" },
  "pri(app.onboardCreatePassword)": { flow: "onboarding" },
  "pri(app.authenticate)": { event: ["app_unlocked", "app_unlock_failed"] },
  "pri(app.lock)": { event: "app_locked" },
  "pri(app.changePassword)": { flow: "password_migration" },
  "pri(app.changePassword.subscribe)": { flow: "password_change" },
  "pri(app.checkPassword)": "read",
  "pri(app.dashboardOpen)": { exempt: "navigation" },
  "pri(app.onboardOpen)": { exempt: "navigation" },
  "pri(app.popupOpen)": { exempt: "navigation" },
  "pri(app.sendFunds.open)": { flow: "send" },
  "pri(app.promptLogin)": { exempt: "navigation" },
  "pri(app.phishing.addException)": { event: "phishing_site_trusted" },
  "pri(app.resetWallet)": { flow: "wallet_reset" },
  "pri(app.quickUnlock.enroll)": { flow: "quick_unlock_setup" },
  "pri(app.quickUnlock.unenroll)": { event: "quick_unlock_disabled" },
  "pri(app.quickUnlock.getCredentialInfo)": "read",
  "pri(app.quickUnlock.authenticate)": { event: ["app_unlocked", "app_unlock_failed"] },
  "pri(sites.requests.approve)": { event: ["dapp_request_resolved", "dapp_connection_approved"] },
  "pri(sites.requests.reject)": { event: "dapp_request_resolved" },
  "pri(sites.requests.ignore)": { event: "dapp_request_resolved" },
  "pri(sites.requests.approveSolSignIn)": {
    event: ["dapp_request_resolved", "dapp_connection_approved"],
  },
  "pri(sites.forget)": { exempt: "pending 5e" },
  "pri(sites.update)": { event: ["dapp_connection_updated", "dapp_network_switched"] },
  "pri(sites.disconnect.all)": { exempt: "pending 5e" },
  "pri(sites.forget.all)": { exempt: "pending 5e" },
  "pri(balances.get)": "read",
  "pri(polkadotVault.generateQr.addNetworkSpecs)": "read",
  "pri(polkadotVault.generateQr.updateNetworkMetadata)": "read",
  "pri(eth.request)": "read",
  "pri(eth.transactions.count)": "read",
  "pri(eth.signing.signAndSend)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(eth.signing.sendSigned)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(eth.signing.cancel)": { event: "dapp_request_resolved" },
  "pri(eth.signing.approveSign)": { event: "dapp_request_resolved" },
  "pri(eth.signing.approveSignAndSend)": {
    event: ["tx_signed", "tx_broadcast", "dapp_request_resolved"],
  },
  "pri(eth.signing.approveSignHardware)": { event: "dapp_request_resolved" },
  "pri(eth.signing.approveSignAndSendHardware)": {
    event: ["tx_signed", "tx_broadcast", "dapp_request_resolved"],
  },
  "pri(eth.networks.add.approve)": {
    event: ["dapp_request_resolved", "custom_network_saved", "network_toggled"],
  },
  "pri(eth.networks.add.cancel)": { event: "dapp_request_resolved" },
  "pri(eth.watchasset.requests.approve)": {
    event: ["dapp_request_resolved", "custom_token_added", "token_toggled"],
  },
  "pri(eth.watchasset.requests.cancel)": { event: "dapp_request_resolved" },
  "pri(mnemonics.unlock)": "read",
  "pri(mnemonics.confirm)": { flow: "recovery_phrase_backup" },
  "pri(mnemonics.rename)": { event: "item_renamed" },
  "pri(mnemonics.delete)": { event: "recovery_phrase_deleted" },
  "pri(mnemonics.validateMnemonic)": "read",
  "pri(mnemonics.setVerifierCertMnemonic)": { event: "verifier_certificate_set" },
  "pri(signing.approveSign)": { event: ["tx_signed", "dapp_request_resolved"] },
  "pri(signing.approveSign.hardware)": { event: ["tx_signed", "dapp_request_resolved"] },
  "pri(signing.approveSign.qr)": { event: ["tx_signed", "dapp_request_resolved"] },
  "pri(signing.approveSign.signet)": { event: "dapp_request_resolved" },
  "pri(signing.approveSign.vrf)": { event: "dapp_request_resolved" },
  "pri(signing.cancel)": { event: "dapp_request_resolved" },
  "pri(tokenRates.registerAdditional)": "read",
  "pri(substrate.rpc.send)": "read",
  "pri(substrate.rpc.submit)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(substrate.rpc.submit.withBittensorMevShield)": {
    event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"],
  },
  "pri(substrate.metadata.get)": "read",
  "pri(solana.rpc.send)": "read",
  "pri(solana.rpc.submit)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(solana.sign.approve)": { event: ["tx_signed", "tx_broadcast", "dapp_request_resolved"] },
  "pri(solana.sign.cancel)": { event: "dapp_request_resolved" },
  "pri(nfts.collection.setHidden)": { exempt: "pending 5e" },
  "pri(nfts.setFavorite)": { exempt: "pending 5e" },
  "pri(nfts.refreshMetadata)": { exempt: "pending 5e" },
  "pri(earn.yieldxyz.positions.refresh)": "read",
  "pri(keepalive)": { exempt: "housekeeping" },
  "pri(keepunlocked)": { exempt: "housekeeping" },
  "pri(chaindata.networks.upsert)": { exempt: "pending 5e" },
  "pri(chaindata.networks.remove)": { exempt: "pending 5e" },
  "pri(chaindata.tokens.upsert)": { exempt: "pending 5e" },
  "pri(chaindata.tokens.remove)": { exempt: "pending 5e" },
  "pri(sendFunds.confirmedAddresses.add)": { flow: "send" },
  "pri(queryCache.get)": "read",
  "pri(queryCache.set)": { exempt: "transport" },
  "pri(queryCache.remove)": { exempt: "transport" },
  "pri(unsubscribe)": { exempt: "transport" },
} as const satisfies MessageCoverage
