import type { Coverage } from "@common/analytics/coverage"

import type { MessageTypes, MessageTypesWithSubscriptions } from "../../types"

type PriMessage = Extract<MessageTypes, `pri(${string})`>
type PriSubscription = Extract<MessageTypesWithSubscriptions, `pri(${string})`>

/** Subscriptions are reads unless listed: one that writes must say what it sends. */
type MessageCoverage = { readonly [M in Exclude<PriMessage, PriSubscription>]: Coverage } & {
  readonly [M in PriSubscription]?: Exclude<Coverage, "read">
}

export const MESSAGE_COVERAGE = {
  "pri(accounts.add.external)": { exempt: "pending 5a" },
  "pri(accounts.add.derive)": { exempt: "pending 5a" },
  "pri(accounts.add.keypair)": { exempt: "pending 5a" },
  "pri(accounts.create.json)": { exempt: "pending 5a" },
  "pri(accounts.forget)": { exempt: "pending 5a" },
  "pri(accounts.export)": { exempt: "pending 5a" },
  "pri(accounts.export.all)": { exempt: "pending 5a" },
  "pri(accounts.export.pk)": { exempt: "pending 5a" },
  "pri(accounts.rename)": { exempt: "pending 5a" },
  "pri(accounts.update.contact)": { exempt: "pending 5e" },
  "pri(accounts.external.setIsPortfolio)": { exempt: "pending 5a" },
  "pri(accounts.catalog.runActions)": { exempt: "pending 5a" },
  "pri(accounts.address.lookup)": "read",
  "pri(accounts.derivationPath.next)": "read",
  "pri(accounts.onChainIds.resolveNames)": "read",
  "pri(accounts.onChainIds.lookupAddresses)": "read",
  "pri(accountProxies.refresh)": "read",
  "pri(accountProxies.loadDetails)": "read",
  "pri(accountProxies.updatePalletCache)": "read",
  "pri(analytics.track)": { exempt: "transport" },
  "pri(analytics.requestRisk)": { event: "dapp_request_resolved" },
  "pri(app.onboardCreatePassword)": { exempt: "pending 5a" },
  "pri(app.authenticate)": { event: "app_unlocked" },
  "pri(app.lock)": { event: "app_locked" },
  "pri(app.changePassword)": { exempt: "pending 5a" },
  "pri(app.changePassword.subscribe)": { exempt: "pending 5a" },
  "pri(app.checkPassword)": "read",
  "pri(app.dashboardOpen)": { exempt: "navigation" },
  "pri(app.onboardOpen)": { exempt: "navigation" },
  "pri(app.popupOpen)": { exempt: "navigation" },
  "pri(app.sendFunds.open)": { exempt: "pending 5b" },
  "pri(app.promptLogin)": { exempt: "navigation" },
  "pri(app.phishing.addException)": { exempt: "pending 5c" },
  "pri(app.resetWallet)": { exempt: "pending 5a" },
  "pri(app.quickUnlock.enroll)": { exempt: "pending 5a" },
  "pri(app.quickUnlock.unenroll)": { exempt: "pending 5a" },
  "pri(app.quickUnlock.getCredentialInfo)": "read",
  "pri(app.quickUnlock.authenticate)": { event: "app_unlocked" },
  "pri(sites.requests.approve)": { event: "dapp_request_resolved" },
  "pri(sites.requests.reject)": { event: "dapp_request_resolved" },
  "pri(sites.requests.ignore)": { event: "dapp_request_resolved" },
  "pri(sites.requests.approveSolSignIn)": { event: "dapp_request_resolved" },
  "pri(sites.forget)": { exempt: "pending 5e" },
  "pri(sites.update)": { exempt: "pending 5c" },
  "pri(sites.disconnect.all)": { exempt: "pending 5e" },
  "pri(sites.forget.all)": { exempt: "pending 5e" },
  "pri(balances.get)": "read",
  "pri(polkadotVault.generateQr.addNetworkSpecs)": "read",
  "pri(polkadotVault.generateQr.updateNetworkMetadata)": "read",
  "pri(eth.request)": "read",
  "pri(eth.transactions.count)": "read",
  "pri(eth.signing.signAndSend)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(eth.signing.sendSigned)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(eth.signing.cancel)": { event: "dapp_request_resolved" },
  "pri(eth.signing.approveSign)": { event: "dapp_request_resolved" },
  "pri(eth.signing.approveSignAndSend)": {
    event: ["tx_signed", "tx_broadcast", "dapp_request_resolved"],
  },
  "pri(eth.signing.approveSignHardware)": { event: "dapp_request_resolved" },
  "pri(eth.signing.approveSignAndSendHardware)": {
    event: ["tx_signed", "tx_broadcast", "dapp_request_resolved"],
  },
  "pri(eth.networks.add.approve)": { event: "dapp_request_resolved" },
  "pri(eth.networks.add.cancel)": { event: "dapp_request_resolved" },
  "pri(eth.watchasset.requests.approve)": { event: "dapp_request_resolved" },
  "pri(eth.watchasset.requests.cancel)": { event: "dapp_request_resolved" },
  "pri(mnemonics.unlock)": { exempt: "pending 5a" },
  "pri(mnemonics.confirm)": { flow: "recovery_phrase_backup" },
  "pri(mnemonics.rename)": { exempt: "pending 5a" },
  "pri(mnemonics.delete)": { exempt: "pending 5a" },
  "pri(mnemonics.validateMnemonic)": "read",
  "pri(mnemonics.setVerifierCertMnemonic)": { exempt: "pending 5a" },
  "pri(signing.approveSign)": { event: ["tx_signed", "dapp_request_resolved"] },
  "pri(signing.approveSign.hardware)": { event: ["tx_signed", "dapp_request_resolved"] },
  "pri(signing.approveSign.qr)": { event: ["tx_signed", "dapp_request_resolved"] },
  "pri(signing.approveSign.signet)": { event: "dapp_request_resolved" },
  "pri(signing.approveSign.vrf)": { event: "dapp_request_resolved" },
  "pri(signing.cancel)": { event: "dapp_request_resolved" },
  "pri(tokenRates.registerAdditional)": "read",
  "pri(substrate.rpc.send)": "read",
  "pri(substrate.rpc.submit)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(substrate.rpc.submit.withBittensorMevShield)": {
    event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"],
  },
  "pri(substrate.metadata.get)": "read",
  "pri(solana.rpc.send)": "read",
  "pri(solana.rpc.submit)": { event: ["tx_signed", "tx_broadcast", "tx_broadcast_failed"] },
  "pri(solana.sign.approve)": { event: ["tx_signed", "tx_broadcast", "dapp_request_resolved"] },
  "pri(nfts.collection.setHidden)": { exempt: "pending 5e" },
  "pri(nfts.setFavorite)": { exempt: "pending 5e" },
  "pri(nfts.refreshMetadata)": { exempt: "pending 5e" },
  "pri(earn.yieldxyz.positions.refresh)": "read",
  "pri(keepalive)": { exempt: "housekeeping" },
  "pri(keepunlocked)": { exempt: "housekeeping" },
  "pri(chaindata.networks.upsert)": { exempt: "pending 5e" },
  "pri(chaindata.networks.remove)": { exempt: "pending 5e" },
  "pri(chaindata.tokens.upsert)": { exempt: "pending 5e" },
  "pri(chaindata.tokens.remove)": { exempt: "pending 5e" },
  "pri(sendFunds.confirmedAddresses.add)": { exempt: "pending 5b" },
  "pri(queryCache.get)": "read",
  "pri(queryCache.set)": { exempt: "transport" },
  "pri(queryCache.remove)": { exempt: "transport" },
  "pri(unsubscribe)": { exempt: "transport" },
} as const satisfies MessageCoverage
