import { assert } from "@talismn/util"
import md5 from "blueimp-md5"

import { type Migration, MigrationFunction } from "../../../libs/migrations/types"
import { appStore } from "../../app/store.app"
import { getLegacyPjsAccountEntries, saveLegacyPjsAccount } from "../../keyring/legacyPjsAccounts"
import { decryptMnemonic } from "../legacy/helpers"
import {
  createLegacySeedPhraseStore,
  createLegacyVerifierCertificateMnemonicStore,
} from "../legacy/store"
import { encryptMnemonic, MnemonicSource, mnemonicsStore } from "../store"

type AccountType = {
  [K in keyof typeof AccountTypes]: (typeof AccountTypes)[K]
}[keyof typeof AccountTypes]

const AccountTypes = {
  TALISMAN: "TALISMAN", // mnemonic generated by Talisman
  LEGACY_ROOT: "ROOT", // legacy, deprecated
  DERIVED: "DERIVED",
  SEED_STORED: "SEED_STORED", // used for an imported mnemonic which is stored
} as const

const mnemonicAccountTypes: AccountType[] = [
  AccountTypes.TALISMAN,
  AccountTypes.LEGACY_ROOT,
  AccountTypes.SEED_STORED,
]

const getMnemonicHash = async (cipher: string, password: string) => {
  const { val: mnemonic, err } = await decryptMnemonic(cipher, password)
  if (err) throw new Error(mnemonic)
  const hash = md5(mnemonic)

  const encrypted = await encryptMnemonic(mnemonic, password)
  return { hash, encrypted }
}

export const migrateSeedStoreToMultiple: Migration = {
  forward: new MigrationFunction(async (context) => {
    const legacyStore = createLegacySeedPhraseStore()
    const legacyData = await legacyStore.get()
    const legacyCipher = legacyData.cipher
    if (!legacyCipher) return

    const { password } = context
    assert(password, "Password not found, unable to perform migration")

    const { encrypted: cipher, hash: id } = await getMnemonicHash(legacyCipher, password)

    await mnemonicsStore.set({
      [id]: {
        id,
        name: "My Recovery Phrase",
        source: MnemonicSource.Legacy,
        cipher,
        confirmed: legacyData.confirmed,
      },
    })

    // get all accounts which have been derived from this recovery phrase, and add derivedMnemonicId to the metadata
    // operates on the legacy pjs keyring storage: this migration predates (and runs before) migrateFromPjsKeyring

    const allAccountEntries = await getLegacyPjsAccountEntries()
    const parentEntry = allAccountEntries.find(
      ([, account]) =>
        account.meta.origin && mnemonicAccountTypes.includes(account.meta.origin as AccountType)
    )
    const derivedEntries = allAccountEntries.filter(
      ([, account]) =>
        account.meta.parent === parentEntry?.[1].address &&
        account.meta.origin === AccountTypes.DERIVED
    )
    const migrationEntries = [...derivedEntries, parentEntry]

    for (const entry of migrationEntries) {
      if (entry) {
        const [key, account] = entry
        await saveLegacyPjsAccount(key, {
          ...account,
          meta: { ...account.meta, derivedMnemonicId: id },
        })
      }
    }

    // if a verifier certificate exists, add it to the new seed store
    const legacyVerifierCertificateStore = createLegacyVerifierCertificateMnemonicStore()
    const legacyVCData = await legacyVerifierCertificateStore.get()
    if (legacyVCData.cipher) {
      let appStoreVCId = id
      if (legacyVCData.cipher !== legacyData.cipher) {
        const { encrypted: vcCipher, hash: vcId } = await getMnemonicHash(
          legacyVCData.cipher,
          password
        )

        appStoreVCId = vcId

        await mnemonicsStore.set({
          [vcId]: {
            ...legacyVCData,
            id: vcId,
            name: "Polkadot Vault Verifier Certificate",
            source: MnemonicSource.Legacy,
            cipher: vcCipher,
            confirmed: true, // verifier certificate is always confirmed, because it was imported manually
          },
        })
      }

      // set the app store to use the new id
      await appStore.set({ vaultVerifierCertificateMnemonicId: appStoreVCId })
    }
  }),
  // no way back
}

const _migrations = {
  0: migrateSeedStoreToMultiple,
}
