enableImmutableInstalls: false
enableProgressBars: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
