import type {
  AccountJson,
  RequestAccountSubscribe,
  ResponseAccountExport,
  ResponseAccountsExport,
} from "@polkadot/extension-base/background/types"
import { KeyringPair$Json } from "@polkadot/keyring/types"
import { TokenId } from "@talismn/chaindata-provider"
import { KeypairCurve } from "@talismn/crypto"
import {
  Account,
  AddAccountDeriveOptions,
  AddAccountExternalOptions,
  AddAccountKeypairOptions,
} from "@talismn/keyring"
import { NsLookupType } from "@talismn/on-chain-id"
import { HexString } from "@talismn/util"

import type { RequestAccountsCatalogAction, Trees } from "./helpers.catalog"
import { Address } from "../../types/base"

export type { RequestAccountsCatalogAction } from "./helpers.catalog"
export type { AccountJson, ResponseAccountExport }

export type { RequestAccountList } from "@polkadot/extension-base/background/types"

// account types ----------------------------------

/** @deprecated */
type AccountJsonHardwareSubstrateOwnProperties = {
  isHardware: true
  accountIndex: number
  addressOffset: number
  ledgerApp?: SubstrateLedgerAppType
  migrationAppName?: string
}

/** @deprecated */
export type AccountJsonHardwareSubstrate = AccountJson & AccountJsonHardwareSubstrateOwnProperties

/** @deprecated */
type AccountJsonHardwareEthereumOwnProperties = {
  isHardware: true
  path: string
}

/** @deprecated */
export type AccountJsonHardwareEthereum = AccountJson & AccountJsonHardwareEthereumOwnProperties

/** @deprecated */
type AccountJsonHardwarePolkadotOwnProperties = {
  isHardware: true
  path: string
}
/** @deprecated */
export type AccountJsonHardwarePolkadot = AccountJson & AccountJsonHardwarePolkadotOwnProperties

/** @deprecated */
type AccountJsonQrOwnProperties = {
  isQr: true
}
/** @deprecated */
export type AccountJsonQr = AccountJson & AccountJsonQrOwnProperties

/** @deprecated */
type AccountJsonWatchedOwnProperties = {
  isPortfolio: boolean
}

/** @deprecated */
export type AccountJsonWatched = AccountJson & AccountJsonWatchedOwnProperties

/** @deprecated */
type AccountJsonDcentOwnProperties = {
  path: string
  tokenIds: TokenId[]
}

/** @deprecated */
export type AccountJsonDcent = AccountJson & AccountJsonDcentOwnProperties

/** @deprecated */
type AccountJsonSignetOwnProperties = {
  signetUrl: string
}

/** @deprecated */
export type AccountJsonSignet = AccountJson & AccountJsonSignetOwnProperties

export type IdenticonType = "talisman-orb" | "polkadot-identicon"

export const AccountImportSources = {
  JSON: "json",
  PK: "pk",
} as const

export type AccountImportSource = {
  [K in keyof typeof AccountImportSources]: (typeof AccountImportSources)[K]
}[keyof typeof AccountImportSources]

/** @deprecated */
export enum LegacyAccountOrigin {
  Talisman = "TALISMAN", // mnemonic generated by Talisman
  Qr = "QR",
  Ledger = "LEDGER",
  Dcent = "DCENT",
  Watched = "WATCHED",
  Signet = "SIGNET",
}

/** @deprecated */
export interface AccountMeta extends AccountJson {
  name: string
  origin: LegacyAccountOrigin
  importSource?: AccountImportSource
}

/**
 * @deprecated
 */
export interface LegacyAccount {
  address: Address
  meta: AccountMeta
}

/** @deprecated */
export type AccountsList = LegacyAccount[]

// TODO migrate
/**
 * @deprecated
 */
export enum SubstrateLedgerAppType {
  Legacy = "substrate-legacy",
  Generic = "substrate-generic",
}

export interface RequestAccountCreateFromJson {
  unlockedPairs: KeyringPair$Json[]
}

export interface RequestAccountExternalSetIsPortfolio {
  address: string
  isPortfolio: boolean
}

export interface RequestAccountForget {
  address: string
}

export interface RequestAccountExport {
  address: string
  password: string
  exportPw: string
}

export interface RequestAccountExportAll {
  password: string
  exportPw: string
}

export interface RequestAccountExportPrivateKey {
  address: string
  password: string
}

export interface RequestAccountRename {
  address: string
  name: string
}

export interface RequestAccountContactUpdate {
  address: string
  name: string
  genesisHash?: HexString
}

export type RequestAddressLookupByMnemonic = {
  type: "mnemonic"
  mnemonic: string
  derivationPath: string
  curve: KeypairCurve
}
export type RequestAddressLookupByMnemonicId = {
  type: "mnemonicId"
  mnemonicId: string
  derivationPath: string
  curve: KeypairCurve
}
export type RequestAddressLookup = RequestAddressLookupByMnemonic | RequestAddressLookupByMnemonicId

export type RequestNextDerivationPath = {
  mnemonicId: string
  curve: KeypairCurve
}

export type RequestAddAccountExternal = AddAccountExternalOptions[]
export type RequestAddAccountDerive = AddAccountDeriveOptions[]

type AddAccountKeypairOptionsSerialized = Omit<AddAccountKeypairOptions, "secretKey"> & {
  secretKey: string // serialize as base64 for message passing
}
export type RequestAddAccountKeypair = AddAccountKeypairOptionsSerialized[]

export interface AccountsMessages {
  // account message signatures
  "pri(accounts.add.external)": [RequestAddAccountExternal, string[]]
  "pri(accounts.add.derive)": [RequestAddAccountDerive, string[]]
  "pri(accounts.add.keypair)": [RequestAddAccountKeypair, string[]]
  "pri(accounts.create.json)": [RequestAccountCreateFromJson, string[]] // TODO use add.keypair instead
  "pri(accounts.forget)": [RequestAccountForget, boolean]
  "pri(accounts.export)": [RequestAccountExport, ResponseAccountExport]
  "pri(accounts.export.all)": [RequestAccountExportAll, ResponseAccountsExport]
  "pri(accounts.export.pk)": [RequestAccountExportPrivateKey, string]
  "pri(accounts.rename)": [RequestAccountRename, boolean]
  "pri(accounts.update.contact)": [RequestAccountContactUpdate, boolean]
  "pri(accounts.external.setIsPortfolio)": [RequestAccountExternalSetIsPortfolio, boolean]
  "pri(accounts.subscribe)": [RequestAccountSubscribe, boolean, Account[]]
  "pri(accounts.catalog.subscribe)": [null, boolean, Trees]
  "pri(accounts.catalog.runActions)": [RequestAccountsCatalogAction[], boolean]
  "pri(accounts.address.lookup)": [RequestAddressLookup, string]
  "pri(accounts.derivationPath.next)": [RequestNextDerivationPath, string]
  "pri(accounts.onChainIds.resolveNames)": [string[], Record<string, [string, NsLookupType] | null>]
  "pri(accounts.onChainIds.lookupAddresses)": [string[], Record<string, string | null>]
}
