import type {
  AccountJson,
  RequestAccountSubscribe,
  ResponseAccountExport,
  ResponseAccountsExport,
} from "@polkadot/extension-base/background/types"
import { KeyringPair$Json } from "@polkadot/keyring/types"
import { TokenId } from "@talismn/chaindata-provider"
import { KeypairCurve } from "@talismn/crypto"
import {
  Account,
  AddAccountDeriveOptions,
  AddAccountExternalOptions,
  AddAccountKeypairOptions,
} from "@talismn/keyring"
import { NsLookupType } from "@talismn/on-chain-id"

import type { RequestAccountsCatalogAction, Trees } from "./helpers.catalog"
import { Address } from "../../types/base"

export type { ResponseAccountExport, AccountJson }
export type { RequestAccountsCatalogAction } from "./helpers.catalog"

export type { RequestAccountList } from "@polkadot/extension-base/background/types"

// account types ----------------------------------

type AccountJsonHardwareSubstrateOwnProperties = {
  isHardware: true
  accountIndex: number
  addressOffset: number
  ledgerApp?: SubstrateLedgerAppType
  migrationAppName?: string
}

export type AccountJsonHardwareSubstrate = AccountJson & AccountJsonHardwareSubstrateOwnProperties

type AccountJsonHardwareEthereumOwnProperties = {
  isHardware: true
  path: string
}

export type AccountJsonHardwareEthereum = AccountJson & AccountJsonHardwareEthereumOwnProperties

type AccountJsonHardwarePolkadotOwnProperties = {
  isHardware: true
  path: string
}
export type AccountJsonHardwarePolkadot = AccountJson & AccountJsonHardwarePolkadotOwnProperties

type AccountJsonQrOwnProperties = {
  isQr: true
}

export type AccountJsonQr = AccountJson & AccountJsonQrOwnProperties

type AccountJsonWatchedOwnProperties = {
  isPortfolio: boolean
}

export type AccountJsonWatched = AccountJson & AccountJsonWatchedOwnProperties

type AccountJsonDcentOwnProperties = {
  path: string
  tokenIds: TokenId[]
}

export type AccountJsonDcent = AccountJson & AccountJsonDcentOwnProperties

type AccountJsonSignetOwnProperties = {
  signetUrl: string
}

export type AccountJsonSignet = AccountJson & AccountJsonSignetOwnProperties

export type IdenticonType = "talisman-orb" | "polkadot-identicon"

export const AccountImportSources = {
  JSON: "json",
  PK: "pk",
} as const

export type AccountImportSource = {
  [K in keyof typeof AccountImportSources]: (typeof AccountImportSources)[K]
}[keyof typeof AccountImportSources]

export enum LegacyAccountOrigin {
  Talisman = "TALISMAN", // mnemonic generated by Talisman
  Qr = "QR",
  Ledger = "LEDGER",
  Dcent = "DCENT",
  Watched = "WATCHED",
  Signet = "SIGNET",
}
export interface AccountMeta extends AccountJson {
  name: string
  origin: LegacyAccountOrigin
  importSource?: AccountImportSource
}

/**
 * @deprecated
 */
export interface LegacyAccount {
  address: Address
  meta: AccountMeta
}

export type AccountsList = LegacyAccount[]

// TODO migrate
export enum SubstrateLedgerAppType {
  Legacy = "substrate-legacy",
  Generic = "substrate-generic",
}

export interface RequestAccountCreateFromSuri {
  name: string
  suri: string
  curve?: KeypairCurve
}

export interface RequestAccountCreateFromPrivateKey {
  name: string
  privateKey: string
  curve?: KeypairCurve
}

export interface RequestAccountCreateFromJson {
  unlockedPairs: KeyringPair$Json[]
}

export interface RequestAccountExternalSetIsPortfolio {
  address: string
  isPortfolio: boolean
}

export interface RequestAccountForget {
  address: string
}

export interface RequestAccountExport {
  address: string
  password: string
  exportPw: string
}

export interface RequestAccountExportAll {
  password: string
  exportPw: string
}

export interface RequestAccountExportPrivateKey {
  address: string
  password: string
}

export interface RequestAccountRename {
  address: string
  name: string
}

export type RequestAccountCreateOptionsNewMnemonic = {
  mnemonic: string
  confirmed: boolean
  derivationPath?: string
}

export type RequestAccountCreateOptionsExistingMnemonic = {
  mnemonicId: string
  derivationPath?: string
}

export type RequestAccountCreateOptions =
  | RequestAccountCreateOptionsExistingMnemonic
  | RequestAccountCreateOptionsNewMnemonic

export type RequestAccountCreate = {
  name: string
  curve: KeypairCurve
} & RequestAccountCreateOptions

export type RequestAddressLookupBySuri = {
  suri: string
  curve: KeypairCurve
}
export type RequestAddressLookupByMnemonic = {
  mnemonicId: string
  derivationPath: string
  curve: KeypairCurve
}
export type RequestAddressLookup = RequestAddressLookupBySuri | RequestAddressLookupByMnemonic

export type RequestNextDerivationPath = {
  mnemonicId: string
  curve: KeypairCurve
}

export type RequestAddAccountExternal = AddAccountExternalOptions[]
export type RequestAddAccountDerive = AddAccountDeriveOptions[]

type AddAccountKeypairOptionsSerialized = Omit<AddAccountKeypairOptions, "secretKey"> & {
  secretKey: string // serialize as base64 for message passing
}
export type RequestAddAccountKeypair = AddAccountKeypairOptionsSerialized[]

export interface AccountsMessages {
  // account message signatures
  "pri(accounts.add.external)": [RequestAddAccountExternal, string[]]
  "pri(accounts.add.derive)": [RequestAddAccountDerive, string[]]
  "pri(accounts.add.keypair)": [RequestAddAccountKeypair, string[]]
  "pri(accounts.create)": [RequestAccountCreate, string]
  "pri(accounts.create.suri)": [RequestAccountCreateFromSuri, string]
  "pri(accounts.create.privateKey)": [RequestAccountCreateFromPrivateKey, string]
  "pri(accounts.create.json)": [RequestAccountCreateFromJson, string[]]
  "pri(accounts.forget)": [RequestAccountForget, boolean]
  "pri(accounts.export)": [RequestAccountExport, ResponseAccountExport]
  "pri(accounts.export.all)": [RequestAccountExportAll, ResponseAccountsExport]
  "pri(accounts.export.pk)": [RequestAccountExportPrivateKey, string]
  "pri(accounts.rename)": [RequestAccountRename, boolean]
  "pri(accounts.external.setIsPortfolio)": [RequestAccountExternalSetIsPortfolio, boolean]
  "pri(accounts.subscribe)": [RequestAccountSubscribe, boolean, Account[]]
  "pri(accounts.catalog.subscribe)": [null, boolean, Trees]
  "pri(accounts.catalog.runActions)": [RequestAccountsCatalogAction[], boolean]
  "pri(accounts.address.lookup)": [RequestAddressLookup, string]
  "pri(accounts.derivationPath.next)": [RequestNextDerivationPath, string]
  "pri(accounts.onChainIds.resolveNames)": [string[], Record<string, [string, NsLookupType] | null>]
  "pri(accounts.onChainIds.lookupAddresses)": [string[], Record<string, string | null>]
}
