import { type Migration, MigrationFunction } from "../../../libs/migrations/types"
import { appStore } from "../../app/store.app"
import { getLegacyPjsAccountEntries, saveLegacyPjsAccount } from "../../keyring/legacyPjsAccounts"
import { LegacyAccountOrigin, SubstrateLedgerAppType } from "../types"

const POLKADOT_GENESIS_HASH = "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"

export const LegacyAccountTypes = {
  TALISMAN: "TALISMAN", // mnemonic generated by Talisman
  LEGACY_ROOT: "ROOT", // legacy, deprecated
  DERIVED: "DERIVED",
  SEED: "SEED", // used for an imported mnemonic used to generate accounts but not stored
  SEED_STORED: "SEED_STORED", // used for an imported mnemonic which is stored
  JSON: "JSON",
  QR: "QR",
  HARDWARE: "HARDWARE",
  WATCHED: "WATCHED",
} as const

export type LegacyAccountType = {
  [K in keyof typeof LegacyAccountTypes]: (typeof LegacyAccountTypes)[K]
}[keyof typeof LegacyAccountTypes]

const NewAccountTypes = {
  TALISMAN: "TALISMAN", // all accounts with locally stored private key
  QR: "QR",
  LEDGER: "LEDGER",
  WATCHED: "WATCHED",
}

const accountOriginSwitch = (origin: LegacyAccountType): Record<string, unknown> => {
  switch (origin) {
    case LegacyAccountTypes.TALISMAN:
    case LegacyAccountTypes.LEGACY_ROOT:
    case LegacyAccountTypes.DERIVED:
    case LegacyAccountTypes.SEED:
    case LegacyAccountTypes.SEED_STORED:
      return { origin: NewAccountTypes.TALISMAN }
    case LegacyAccountTypes.JSON:
      return { origin: NewAccountTypes.TALISMAN, importSource: "json" }
    case LegacyAccountTypes.HARDWARE:
      return { origin: NewAccountTypes.LEDGER }
    default:
      return { origin }
  }
}

// operates on the legacy pjs keyring storage: this migration predates (and runs before) migrateFromPjsKeyring
export const migrateToNewAccountTypes: Migration = {
  forward: new MigrationFunction(async () => {
    for (const [key, account] of await getLegacyPjsAccountEntries()) {
      const { origin } = account.meta as {
        origin: LegacyAccountType
      }
      const newMeta = accountOriginSwitch(origin)

      // delete genesisHash for old json-imported accounts
      if (origin === LegacyAccountTypes.JSON && account.meta.genesisHash)
        delete account.meta.genesisHash

      await saveLegacyPjsAccount(key, { ...account, meta: { ...account.meta, ...newMeta } })
    }
  }),
}

// Migrates Polkadot ledger accounts from legacy to generic app
// operates on the legacy pjs keyring storage: this migration predates (and runs before) migrateFromPjsKeyring
export const migratePolkadotLedgerAccounts: Migration = {
  forward: new MigrationFunction(async () => {
    for (const [key, account] of await getLegacyPjsAccountEntries()) {
      if (
        account.meta.hardwareType === "ledger" &&
        account.meta.genesisHash === POLKADOT_GENESIS_HASH
      ) {
        const { name, accountIndex, addressOffset, whenCreated } = account.meta

        // same meta as the previous `keyring.addHardware` based implementation (replaces
        // the whole meta object, dropping genesisHash so the account maps to the generic app)
        const newMeta: Record<string, unknown> = {
          name,
          accountIndex,
          addressOffset,
          origin: LegacyAccountOrigin.Ledger,
          ledgerApp: SubstrateLedgerAppType.Generic,
          type: "ed25519",
          hardwareType: "ledger",
          isHardware: true,
          isExternal: true,
          whenCreated: whenCreated ?? Date.now(),
        }

        await saveLegacyPjsAccount(key, { ...account, meta: newMeta })

        appStore.set({ showLedgerPolkadotGenericMigrationAlert: true })
      }
    }
  }),
}
