// biome-ignore-all lint/suspicious/noConsole: CLI script output
import { writeFileSync } from "node:fs"
import path from "node:path"

import { MINIMETADATA_VERSION } from "@talismn/chaindata-provider"

const COINGECKO_MARKETS_URL =
  "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=250&page=1"
const CHAINDATA_URL = `https://raw.githubusercontent.com/TalismanSociety/chaindata/main/pub/${MINIMETADATA_VERSION}/chaindata.min.json`
const ALLOW_LIST_SIZE = 100
const MIN_EXPECTED_SIZE = 50
const OUTPUT_PATH = path.resolve(__dirname, "../src/core/domains/analytics/tvl/allowList.gen.ts")

const fetchJson = async <T>(url: string): Promise<T> => {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${url}: ${response.status} ${response.statusText}`)
  return (await response.json()) as T
}

type Market = { id: string }
type Chaindata = { tokens: { coingeckoId?: string }[] }

async function generateTvlAllowList() {
  const [markets, stablecoins, chaindata] = await Promise.all([
    fetchJson<Market[]>(COINGECKO_MARKETS_URL),
    fetchJson<Market[]>(`${COINGECKO_MARKETS_URL}&category=stablecoins`),
    fetchJson<Chaindata>(CHAINDATA_URL),
  ])

  const carried = new Set(chaindata.tokens.flatMap((token) => token.coingeckoId ?? []))
  const allowed = markets
    .map((market) => market.id)
    .filter((id) => carried.has(id))
    .slice(0, ALLOW_LIST_SIZE)
  if (allowed.length < MIN_EXPECTED_SIZE)
    throw new Error(`Only ${allowed.length} ids in common with chaindata: the inputs look broken`)

  const allowedSet = new Set(allowed)
  const stable = stablecoins.map((market) => market.id).filter((id) => allowedSet.has(id))

  const list = (ids: string[]) => ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")
  writeFileSync(
    OUTPUT_PATH,
    `// Generated by scripts/generateTvlAllowList.ts (pnpm --filter extension chore:generate-init-data). Do not edit.
// The CoinGecko top ${ALLOW_LIST_SIZE} by market cap (/coins/markets) among the ids chaindata tokens carry,
// and the stablecoins among them (CoinGecko category "stablecoins"). Every install ships the same list.
export const TVL_ALLOW_LIST_GENERATED_AT = "${new Date().toISOString().slice(0, 10)}"

export const TVL_ALLOWED_COINGECKO_IDS: readonly string[] = [
${list(allowed)}
]

export const TVL_STABLECOIN_COINGECKO_IDS: readonly string[] = [
${list(stable)}
]
`
  )
  console.log(`Wrote ${allowed.length} ids (${stable.length} stablecoins) to ${OUTPUT_PATH}`)
}

generateTvlAllowList().catch((err) => {
  console.error("Error:", err)
  process.exit(1)
})
