// Copyright 2017-2022 @polkadot/keyring authors & contributors
// SPDX-License-Identifier: Apache-2.0
import { u8aEq } from "@polkadot/util"
import { jsonDecrypt } from "@polkadot/util-crypto"
import { EncryptedJson } from "@polkadot/util-crypto/types"

// values picked from polkadot keyring
const PKCS8_DIVIDER = new Uint8Array([161, 35, 3, 33, 0])
const PKCS8_HEADER = new Uint8Array([48, 83, 2, 1, 1, 48, 5, 6, 3, 43, 101, 112, 4, 34, 4, 32])
const SEC_LENGTH = 64
const SEED_LENGTH = 32
const SEED_OFFSET = PKCS8_HEADER.length

// Function implementation inspired by these files:
// - https://github.com/polkadot-js/common/blob/8b0f5bf46e3edf2f52001c499ccdd555d5bdf5c2/packages/keyring/src/pair/decode.ts#L13-L56
// - https://github.com/polkadot-js/common/blob/8b0f5bf46e3edf2f52001c499ccdd555d5bdf5c2/packages/util-crypto/src/json/decrypt.ts#L11-L25
// - https://github.com/polkadot-js/common/blob/8b0f5bf46e3edf2f52001c499ccdd555d5bdf5c2/packages/util-crypto/src/json/decryptData.ts#L12-L45
//
// You can compare the output of this function to the output of polkadot-js's implementation using:
// ```ts
// (await import("@polkadot/keyring/cjs/pair/decode")).decodePair(password, jsonDecrypt(json, password), json.encoding.type).secretKey
// ```
//
// NOTE: For ed25519 accounts, this function produces a privateKey of length 64 bytes.
// When using the ed25519 curve to derive a publicKey for this privateKey, we should only take the first 32 bytes:
// - https://github.com/paulmillr/noble-curves/issues/53#issuecomment-1577362759
// - https://github.com/paulmillr/noble-curves/discussions/33#discussioncomment-5685971
// - https://github.com/paulmillr/noble-curves/pull/54
// - https://github.com/paulmillr/noble-curves/issues/88
//
// You will find that we do exactly this inside of `packages/crypto/src/derivation/deriveEd25519.ts`, and upon closer
// inspection you will also find that the publicKey produced by these 32 bytes matches the one generated by polkadot-js.
export const getSecretKeyFromPjsJson = (json: EncryptedJson, password: string) => {
  const decrypted = jsonDecrypt(json, password)

  const header = decrypted.subarray(0, PKCS8_HEADER.length)
  if (!u8aEq(header, PKCS8_HEADER)) throw new Error("Invalid Pkcs8 header found in body")

  // current format (v3)
  let privateKey = decrypted.subarray(SEED_OFFSET, SEED_OFFSET + SEC_LENGTH)
  let divOffset = SEED_OFFSET + SEC_LENGTH
  let divider = decrypted.subarray(divOffset, divOffset + PKCS8_DIVIDER.length)

  // legacy formats (v1, v2)
  if (!u8aEq(divider, PKCS8_DIVIDER)) {
    divOffset = SEED_OFFSET + SEED_LENGTH
    privateKey = decrypted.subarray(SEED_OFFSET, divOffset)
    divider = decrypted.subarray(divOffset, divOffset + PKCS8_DIVIDER.length)

    if (!u8aEq(divider, PKCS8_DIVIDER)) throw new Error("Invalid Pkcs8 divider found in body")
  }

  return privateKey
}
