export { ReactComponent as GetStartedAddAccountIcon } from "./add-account.svg"
export { ReactComponent as GetStartedBuyIcon } from "./buy.svg"
export { ReactComponent as GetStartedReceiveIcon } from "./receive.svg"
export { ReactComponent as GetStartedSwapIcon } from "./swap.svg"
export { ReactComponent as GetStartedTryItIcon } from "./try-it.svg"
