export { ReactComponent as BraveIcon } from "./icons/brave.svg"
export { ReactComponent as CapsLockIcon } from "./icons/caps-lock.svg"
export { ReactComponent as ChainIcon } from "./icons/chain.svg"
export { ReactComponent as CoinsIcon } from "./icons/coins.svg"
export { ReactComponent as CommentIcon } from "./icons/comment.svg"
export { ReactComponent as CursorClickIcon } from "./icons/cursor-click.svg"
export { ReactComponent as CustomTokenGenericIcon } from "./icons/custom-token-generic.svg"
export { ReactComponent as DcentIcon } from "./icons/dcent.svg"
export { ReactComponent as DepositIcon } from "./icons/deposit.svg"
export { ReactComponent as DownloadAlertIcon } from "./icons/download-alert.svg"
export { ReactComponent as DragIcon } from "./icons/drag.svg"
export { ReactComponent as ExtensionButtonIcon } from "./icons/extension-button.svg"
export { ReactComponent as EyePlusIcon } from "./icons/eye-plus.svg"
export { ReactComponent as FileCheckIcon } from "./icons/file-check.svg"
export { ReactComponent as FileSearchIcon } from "./icons/file-search.svg"
export { ReactComponent as FileXIcon } from "./icons/file-x.svg"
export { ReactComponent as HamburgerMenuIcon } from "./icons/hamburger-menu.svg"
export { ReactComponent as HistoryIcon } from "./icons/history.svg"
export { ReactComponent as NetworkUsageDecreasingIcon } from "./icons/network-usage-decreasing.svg"
export { ReactComponent as NetworkUsageHighIcon } from "./icons/network-usage-high.svg"
export { ReactComponent as NetworkUsageIdleIcon } from "./icons/network-usage-idle.svg"
export { ReactComponent as NetworkUsageIncreasingIcon } from "./icons/network-usage-increasing.svg"
export { ReactComponent as PinIcon } from "./icons/pin.svg"
export { ReactComponent as PolkadotVaultIcon } from "./icons/polkadot-vault.svg"
export { ReactComponent as PopupIcon } from "./icons/popup.svg"
export { ReactComponent as QrIcon } from "./icons/qr.svg"
export { ReactComponent as QuestStarIcon } from "./icons/quest-star.svg"
export { ReactComponent as RocketIcon } from "./icons/rocket.svg"
export { ReactComponent as SecretIcon } from "./icons/secret.svg"
export { ReactComponent as ShieldNotOkIcon } from "./icons/shield-nok.svg"
export { ReactComponent as ShieldOkIcon } from "./icons/shield-ok.svg"
export { ReactComponent as ShieldSuccessIcon } from "./icons/shield-success.svg"
export { ReactComponent as ShieldUnavailableIcon } from "./icons/shield-unavailable.svg"
export { ReactComponent as ToolbarFilterIcon } from "./icons/toolbar-filter.svg"
export { ReactComponent as ToolbarListIcon } from "./icons/toolbar-list.svg"
export { ReactComponent as ToolbarSortIcon } from "./icons/toolbar-sort.svg"
export { ReactComponent as ToolbarTilesIcon } from "./icons/toolbar-tiles.svg"
export { ReactComponent as ShieldUnknownIcon } from "./icons/shield-unknown.svg"
export { ReactComponent as ShieldZapIcon } from "./icons/shield-zap.svg"
export { ReactComponent as SignetIcon } from "./icons/signet.svg"
export { ReactComponent as StarsIcon } from "./icons/stars.svg"
export { ReactComponent as SwapIcon } from "./icons/swap.svg"
export { ReactComponent as TableIcon } from "./icons/table.svg"
export { ReactComponent as TalismanHandIcon } from "./icons/talisman-hand.svg"
export { ReactComponent as TryItIcon } from "./icons/try-it.svg"
export { ReactComponent as UsbIcon } from "./icons/usb.svg"
export { ReactComponent as UserRightIcon } from "./icons/user-right.svg"
export { ReactComponent as VoteIcon } from "./icons/vote.svg"

export {
  FiActivity as ActivityIcon,
  FiAirplay as AirplayIcon,
  FiAlertCircle as AlertCircleIcon,
  FiAlertOctagon as AlertOctagonIcon,
  FiAlertTriangle as AlertTriangleIcon,
  FiAlignCenter as AlignCenterIcon,
  FiAlignJustify as AlignJustifyIcon,
  FiAlignLeft as AlignLeftIcon,
  FiAlignRight as AlignRightIcon,
  FiAnchor as AnchorIcon,
  FiAperture as ApertureIcon,
  FiArchive as ArchiveIcon,
  FiArrowDownCircle as ArrowDownCircleIcon,
  FiArrowDownLeft as ArrowDownLeftIcon,
  FiArrowDownRight as ArrowDownRightIcon,
  FiArrowDown as ArrowDownIcon,
  FiArrowLeftCircle as ArrowLeftCircleIcon,
  FiArrowLeft as ArrowLeftIcon,
  FiArrowRightCircle as ArrowRightCircleIcon,
  FiArrowRight as ArrowRightIcon,
  FiArrowUpCircle as ArrowUpCircleIcon,
  FiArrowUpLeft as ArrowUpLeftIcon,
  FiArrowUpRight as ArrowUpRightIcon,
  FiArrowUp as ArrowUpIcon,
  FiAtSign as AtSignIcon,
  FiAward as AwardIcon,
  FiBarChart2 as BarChart2Icon,
  FiBarChart as BarChartIcon,
  FiBatteryCharging as BatteryChargingIcon,
  FiBattery as BatteryIcon,
  FiBellOff as BellOffIcon,
  FiBell as BellIcon,
  FiBluetooth as BluetoothIcon,
  FiBold as BoldIcon,
  FiBookOpen as BookOpenIcon,
  FiBook as BookIcon,
  FiBookmark as BookmarkIcon,
  FiBox as BoxIcon,
  FiBriefcase as BriefcaseIcon,
  FiCalendar as CalendarIcon,
  FiCameraOff as CameraOffIcon,
  FiCamera as CameraIcon,
  FiCast as CastIcon,
  FiCheckCircle as CheckCircleIcon,
  FiCheckSquare as CheckSquareIcon,
  FiCheck as CheckIcon,
  FiChevronDown as ChevronDownIcon,
  FiChevronLeft as ChevronLeftIcon,
  FiChevronRight as ChevronRightIcon,
  FiChevronUp as ChevronUpIcon,
  FiChevronsDown as ChevronsDownIcon,
  FiChevronsLeft as ChevronsLeftIcon,
  FiChevronsRight as ChevronsRightIcon,
  FiChevronsUp as ChevronsUpIcon,
  FiChrome as ChromeIcon,
  FiCircle as CircleIcon,
  FiClipboard as ClipboardIcon,
  FiClock as ClockIcon,
  FiCloudDrizzle as CloudDrizzleIcon,
  FiCloudLightning as CloudLightningIcon,
  FiCloudOff as CloudOffIcon,
  FiCloudRain as CloudRainIcon,
  FiCloudSnow as CloudSnowIcon,
  FiCloud as CloudIcon,
  FiCode as CodeIcon,
  FiCodepen as CodepenIcon,
  FiCodesandbox as CodesandboxIcon,
  FiCoffee as CoffeeIcon,
  FiColumns as ColumnsIcon,
  FiCommand as CommandIcon,
  FiCompass as CompassIcon,
  FiCopy as CopyIcon,
  FiCornerDownLeft as CornerDownLeftIcon,
  FiCornerDownRight as CornerDownRightIcon,
  FiCornerLeftDown as CornerLeftDownIcon,
  FiCornerLeftUp as CornerLeftUpIcon,
  FiCornerRightDown as CornerRightDownIcon,
  FiCornerRightUp as CornerRightUpIcon,
  FiCornerUpLeft as CornerUpLeftIcon,
  FiCornerUpRight as CornerUpRightIcon,
  FiCpu as CpuIcon,
  FiCreditCard as CreditCardIcon,
  FiCrop as CropIcon,
  FiCrosshair as CrosshairIcon,
  FiDatabase as DatabaseIcon,
  FiDelete as DeleteIcon,
  FiDisc as DiscIcon,
  FiDivideCircle as DivideCircleIcon,
  FiDivideSquare as DivideSquareIcon,
  FiDivide as DivideIcon,
  FiDollarSign as DollarSignIcon,
  FiDownloadCloud as DownloadCloudIcon,
  FiDownload as DownloadIcon,
  FiDribbble as DribbbleIcon,
  FiDroplet as DropletIcon,
  FiEdit2 as Edit2Icon,
  FiEdit3 as Edit3Icon,
  FiEdit as EditIcon,
  FiExternalLink as ExternalLinkIcon,
  FiEyeOff as EyeOffIcon,
  FiEye as EyeIcon,
  FiFacebook as FacebookIcon,
  FiFastForward as FastForwardIcon,
  FiFeather as FeatherIcon,
  FiFigma as FigmaIcon,
  FiFileMinus as FileMinusIcon,
  FiFilePlus as FilePlusIcon,
  FiFileText as FileTextIcon,
  FiFile as FileIcon,
  FiFilm as FilmIcon,
  FiFilter as FilterIcon,
  FiFlag as FlagIcon,
  FiFolderMinus as FolderMinusIcon,
  FiFolderPlus as FolderPlusIcon,
  FiFolder as FolderIcon,
  FiFramer as FramerIcon,
  FiFrown as FrownIcon,
  FiGift as GiftIcon,
  FiGitBranch as GitBranchIcon,
  FiGitCommit as GitCommitIcon,
  FiGitMerge as GitMergeIcon,
  FiGitPullRequest as GitPullRequestIcon,
  FiGithub as GithubIcon,
  FiGitlab as GitlabIcon,
  FiGlobe as GlobeIcon,
  FiGrid as GridIcon,
  FiHardDrive as HardDriveIcon,
  FiHash as HashIcon,
  FiHeadphones as HeadphonesIcon,
  FiHeart as HeartIcon,
  FiHelpCircle as HelpCircleIcon,
  FiHexagon as HexagonIcon,
  FiHome as HomeIcon,
  FiImage as ImageIcon,
  FiInbox as InboxIcon,
  FiInfo as InfoIcon,
  FiInstagram as InstagramIcon,
  FiItalic as ItalicIcon,
  FiKey as KeyIcon,
  FiLayers as LayersIcon,
  FiLayout as LayoutIcon,
  FiLifeBuoy as LifeBuoyIcon,
  FiLink2 as Link2Icon,
  FiLink as LinkIcon,
  FiLinkedin as LinkedinIcon,
  FiList as ListIcon,
  FiLoader as LoaderIcon,
  FiLock as LockIcon,
  FiLogIn as LogInIcon,
  FiLogOut as LogOutIcon,
  FiMail as MailIcon,
  FiMapPin as MapPinIcon,
  FiMap as MapIcon,
  FiMaximize2 as Maximize2Icon,
  FiMaximize as MaximizeIcon,
  FiMeh as MehIcon,
  FiMenu as MenuIcon,
  FiMessageCircle as MessageCircleIcon,
  FiMessageSquare as MessageSquareIcon,
  FiMicOff as MicOffIcon,
  FiMic as MicIcon,
  FiMinimize2 as Minimize2Icon,
  FiMinimize as MinimizeIcon,
  FiMinusCircle as MinusCircleIcon,
  FiMinusSquare as MinusSquareIcon,
  FiMinus as MinusIcon,
  FiMonitor as MonitorIcon,
  FiMoon as MoonIcon,
  FiMoreHorizontal as MoreHorizontalIcon,
  FiMoreVertical as MoreVerticalIcon,
  FiMousePointer as MousePointerIcon,
  FiMove as MoveIcon,
  FiMusic as MusicIcon,
  FiNavigation2 as Navigation2Icon,
  FiNavigation as NavigationIcon,
  FiOctagon as OctagonIcon,
  FiPackage as PackageIcon,
  FiPaperclip as PaperclipIcon,
  FiPauseCircle as PauseCircleIcon,
  FiPause as PauseIcon,
  FiPenTool as PenToolIcon,
  FiPercent as PercentIcon,
  FiPhoneCall as PhoneCallIcon,
  FiPhoneForwarded as PhoneForwardedIcon,
  FiPhoneIncoming as PhoneIncomingIcon,
  FiPhoneMissed as PhoneMissedIcon,
  FiPhoneOff as PhoneOffIcon,
  FiPhoneOutgoing as PhoneOutgoingIcon,
  FiPhone as PhoneIcon,
  FiPieChart as PieChartIcon,
  FiPlayCircle as PlayCircleIcon,
  FiPlay as PlayIcon,
  FiPlusCircle as PlusCircleIcon,
  FiPlusSquare as PlusSquareIcon,
  FiPlus as PlusIcon,
  FiPocket as PocketIcon,
  FiPower as PowerIcon,
  FiPrinter as PrinterIcon,
  FiRadio as RadioIcon,
  FiRefreshCcw as RefreshCcwIcon,
  FiRefreshCw as RefreshCwIcon,
  FiRepeat as RepeatIcon,
  FiRewind as RewindIcon,
  FiRotateCcw as RotateCcwIcon,
  FiRotateCw as RotateCwIcon,
  FiRss as RssIcon,
  FiSave as SaveIcon,
  FiScissors as ScissorsIcon,
  FiSearch as SearchIcon,
  FiSend as SendIcon,
  FiServer as ServerIcon,
  FiSettings as SettingsIcon,
  FiShare2 as Share2Icon,
  FiShare as ShareIcon,
  FiShieldOff as ShieldOffIcon,
  FiShield as ShieldIcon,
  FiShoppingBag as ShoppingBagIcon,
  FiShoppingCart as ShoppingCartIcon,
  FiShuffle as ShuffleIcon,
  FiSidebar as SidebarIcon,
  FiSkipBack as SkipBackIcon,
  FiSkipForward as SkipForwardIcon,
  FiSlack as SlackIcon,
  FiSlash as SlashIcon,
  FiSliders as SlidersIcon,
  FiSmartphone as SmartphoneIcon,
  FiSmile as SmileIcon,
  FiSpeaker as SpeakerIcon,
  FiSquare as SquareIcon,
  FiStar as StarIcon,
  FiStopCircle as StopCircleIcon,
  FiSun as SunIcon,
  FiSunrise as SunriseIcon,
  FiSunset as SunsetIcon,
  FiTablet as TabletIcon,
  FiTag as TagIcon,
  FiTarget as TargetIcon,
  FiTerminal as TerminalIcon,
  FiThermometer as ThermometerIcon,
  FiThumbsDown as ThumbsDownIcon,
  FiThumbsUp as ThumbsUpIcon,
  FiToggleLeft as ToggleLeftIcon,
  FiToggleRight as ToggleRightIcon,
  FiTool as ToolIcon,
  FiTrash2 as Trash2Icon,
  FiTrash as TrashIcon,
  FiTrello as TrelloIcon,
  FiTrendingDown as TrendingDownIcon,
  FiTrendingUp as TrendingUpIcon,
  FiTriangle as TriangleIcon,
  FiTruck as TruckIcon,
  FiTv as TvIcon,
  FiTwitch as TwitchIcon,
  FiTwitter as TwitterIcon,
  FiType as TypeIcon,
  FiUmbrella as UmbrellaIcon,
  FiUnderline as UnderlineIcon,
  FiUnlock as UnlockIcon,
  FiUploadCloud as UploadCloudIcon,
  FiUpload as UploadIcon,
  FiUserCheck as UserCheckIcon,
  FiUserMinus as UserMinusIcon,
  FiUserPlus as UserPlusIcon,
  FiUserX as UserXIcon,
  FiUser as UserIcon,
  FiUsers as UsersIcon,
  FiVideoOff as VideoOffIcon,
  FiVideo as VideoIcon,
  FiVoicemail as VoicemailIcon,
  FiVolume1 as Volume1Icon,
  FiVolume2 as Volume2Icon,
  FiVolumeX as VolumeXIcon,
  FiVolume as VolumeIcon,
  FiWatch as WatchIcon,
  FiWifiOff as WifiOffIcon,
  FiWifi as WifiIcon,
  FiWind as WindIcon,
  FiXCircle as XCircleIcon,
  FiXOctagon as XOctagonIcon,
  FiXSquare as XSquareIcon,
  FiX as XIcon,
  FiYoutube as YoutubeIcon,
  FiZapOff as ZapOffIcon,
  FiZap as ZapIcon,
  FiZoomIn as ZoomInIcon,
  FiZoomOut as ZoomOutIcon,
} from "react-icons/fi"

export { IoDiamondOutline as DiamondIcon, IoScale as ScaleIcon } from "react-icons/io5"

export { AiOutlineQuestion as QuestionCircleIcon } from "react-icons/ai"
