/*
// When changes to the data expected from the chains gql endpoint are made, please update the following object by copying and pasting the data from 
// @core/domains/chains/api.graphqlUrl with the query given at @core/domains/chains/api.chaindataQuery
*/
const mock = {
  data: {
    chains: [
      {
        id: "polkadot",
        isTestnet: false,
        sortIndex: 1,
        genesisHash: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
        prefix: 0,
        name: "Polkadot",
        chainName: "Polkadot",
        implName: "parity-polkadot",
        specName: "polkadot",
        specVersion: "9220",
        nativeToken: {
          id: "polkadot-native-dot",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://polkadot.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://polkadot-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [
          {
            id: "statemint",
            paraId: 1000,
          },
          {
            id: "acala",
            paraId: 2000,
          },
          {
            id: "bifrost-dot",
            paraId: 2001,
          },
          {
            id: "clover",
            paraId: 2002,
          },
          {
            id: "darwinia",
            paraId: 2003,
          },
          {
            id: "moonbeam",
            paraId: 2004,
          },
          {
            id: "astar",
            paraId: 2006,
          },
          {
            id: "crust",
            paraId: 2008,
          },
          {
            id: "equilibrium",
            paraId: 2011,
          },
          {
            id: "parallel",
            paraId: 2012,
          },
          {
            id: "litentry",
            paraId: 2013,
          },
          {
            id: "manta",
            paraId: 2015,
          },
          {
            id: "subgame",
            paraId: 2017,
          },
          {
            id: "subdao",
            paraId: 2018,
          },
          {
            id: "composable-finance",
            paraId: 2019,
          },
          {
            id: "efinity",
            paraId: 2021,
          },
          {
            id: "nodle",
            paraId: 2026,
          },
          {
            id: "coinversation",
            paraId: 2027,
          },
          {
            id: "ares",
            paraId: 2028,
          },
          {
            id: "centrifuge",
            paraId: 2031,
          },
          {
            id: "interlay",
            paraId: 2032,
          },
          {
            id: "hydradx",
            paraId: 2034,
          },
          {
            id: "phala",
            paraId: 2035,
          },
          {
            id: "polkadex",
            paraId: 2040,
          },
        ],
        paraId: null,
        relay: null,
      },
      {
        id: "kusama",
        isTestnet: false,
        sortIndex: 2,
        genesisHash: "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe",
        prefix: 2,
        name: "Kusama",
        chainName: "Kusama",
        implName: "parity-kusama",
        specName: "kusama",
        specVersion: "9230",
        nativeToken: {
          id: "kusama-native-ksm",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://kusama.subscan.io/",
        rpcs: [
          {
            url: "wss://kusama-rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://kusama-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [
          {
            id: "statemine",
            paraId: 1000,
          },
          {
            id: "encointer",
            paraId: 1001,
          },
          {
            id: "karura",
            paraId: 2000,
          },
          {
            id: "bifrost-ksm",
            paraId: 2001,
          },
          {
            id: "khala",
            paraId: 2004,
          },
          {
            id: "darwinia-crab-redirect",
            paraId: 2006,
          },
          {
            id: "shiden",
            paraId: 2007,
          },
          {
            id: "mars",
            paraId: 2008,
          },
          {
            id: "polkasmith",
            paraId: 2009,
          },
          {
            id: "sora-kusama",
            paraId: 2011,
          },
          {
            id: "crust-shadow",
            paraId: 2012,
          },
          {
            id: "sherpax",
            paraId: 2013,
          },
          {
            id: "encointer-canary",
            paraId: 2014,
          },
          {
            id: "integritee",
            paraId: 2015,
          },
          {
            id: "sakura",
            paraId: 2016,
          },
          {
            id: "subgame-gamma",
            paraId: 2018,
          },
          {
            id: "kpron",
            paraId: 2019,
          },
          {
            id: "moonriver",
            paraId: 2023,
          },
          {
            id: "genshiro",
            paraId: 2024,
          },
          {
            id: "robonomics",
            paraId: 2048,
          },
          {
            id: "loom",
            paraId: 2080,
          },
          {
            id: "calamari",
            paraId: 2084,
          },
          {
            id: "parallel-heiko",
            paraId: 2085,
          },
          {
            id: "kilt-spiritnet",
            paraId: 2086,
          },
          {
            id: "picasso",
            paraId: 2087,
          },
          {
            id: "altair",
            paraId: 2088,
          },
          {
            id: "basilisk",
            paraId: 2090,
          },
          {
            id: "kintsugi-btc",
            paraId: 2092,
          },
          {
            id: "unorthodox",
            paraId: 2094,
          },
          {
            id: "quartz",
            paraId: 2095,
          },
          {
            id: "bit-country-pioneer",
            paraId: 2096,
          },
          {
            id: "subsocialx",
            paraId: 2100,
          },
          {
            id: "zeitgeist",
            paraId: 2101,
          },
          {
            id: "pichiu",
            paraId: 2102,
          },
          {
            id: "darwinia-crab",
            paraId: 2105,
          },
          {
            id: "litmus",
            paraId: 2106,
          },
          {
            id: "kico",
            paraId: 2107,
          },
          {
            id: "turing",
            paraId: 2114,
          },
        ],
        paraId: null,
        relay: null,
      },
      {
        id: "acala",
        isTestnet: false,
        sortIndex: 3,
        genesisHash: "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c",
        prefix: 10,
        name: "Acala",
        chainName: "Acala",
        implName: "acala",
        specName: "acala",
        specVersion: "2064",
        nativeToken: {
          id: "acala-native-aca",
        },
        tokens: [
          {
            id: "acala-orml-aca",
          },
          {
            id: "acala-orml-ausd",
          },
          {
            id: "acala-orml-dot",
          },
          {
            id: "acala-orml-ldot",
          },
        ],
        account: "*25519",
        subscanUrl: "https://acala.subscan.io/",
        rpcs: [
          {
            url: "wss://acala-rpc-0.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc-1.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc-2.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc-3.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://acala.polkawallet.io",
            isHealthy: true,
          },
          {
            url: "wss://acala-polkadot.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2000,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "aleph-zero",
        isTestnet: false,
        sortIndex: 4,
        genesisHash: "0x70255b4d28de0fc4e1a193d7e175ad1ccef431598211c55538f1018651a0344e",
        prefix: 42,
        name: "Aleph Zero",
        chainName: "Aleph Zero",
        implName: "aleph-node",
        specName: "aleph-node",
        specVersion: "12",
        nativeToken: {
          id: "aleph-zero-native-azero",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://ws.azero.dev",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "altair",
        isTestnet: false,
        sortIndex: 5,
        genesisHash: "0xaa3876c1dc8a1afcc2e9a685a49ff7704cfd36ad8c90bf2702b9d1b00cc40011",
        prefix: 42,
        name: "Altair",
        chainName: "Altair",
        implName: "altair",
        specName: "altair",
        specVersion: "1014",
        nativeToken: {
          id: "altair-native-air",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://altair.subscan.io/",
        rpcs: [
          {
            url: "wss://fullnode.altair.centrifuge.io",
            isHealthy: true,
          },
          {
            url: "wss://altair.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2088,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "ares",
        isTestnet: false,
        sortIndex: 7,
        genesisHash: null,
        prefix: null,
        name: "Ares",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://wss.odyssey.aresprotocol.io",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2028,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "astar",
        isTestnet: false,
        sortIndex: 8,
        genesisHash: "0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6",
        prefix: 5,
        name: "Astar",
        chainName: "Astar",
        implName: "astar",
        specName: "astar",
        specVersion: "18",
        nativeToken: {
          id: "astar-native-astr",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://astar.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.astar.network",
            isHealthy: true,
          },
          {
            url: "wss://astar.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://astar-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [
          {
            id: "592",
          },
        ],
        parathreads: [],
        paraId: 2006,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "basilisk",
        isTestnet: false,
        sortIndex: 10,
        genesisHash: "0xa85cfb9b9fd4d622a5b28289a02347af987d8f73fa3108450e2b4a11c1ce5755",
        prefix: 42,
        name: "Basilisk",
        chainName: "Basilisk",
        implName: "basilisk",
        specName: "basilisk",
        specVersion: "43",
        nativeToken: {
          id: "basilisk-native-bsx",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc-01.basilisk.hydradx.io",
            isHealthy: false,
          },
          {
            url: "wss://basilisk.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://basilisk-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2090,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "bifrost-dot",
        isTestnet: false,
        sortIndex: 11,
        genesisHash: null,
        prefix: null,
        name: "Bifrost",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://bifrost-dot.liebi.com/ws",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2001,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "bifrost-ksm",
        isTestnet: false,
        sortIndex: 12,
        genesisHash: "0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed",
        prefix: 6,
        name: "Bifrost",
        chainName: "Bifrost",
        implName: "bifrost",
        specName: "bifrost",
        specVersion: "944",
        nativeToken: {
          id: "bifrost-ksm-native-bnc",
        },
        tokens: [
          {
            id: "bifrost-ksm-orml-bnc",
          },
          {
            id: "bifrost-ksm-orml-dot",
          },
          {
            id: "bifrost-ksm-orml-kar",
          },
          {
            id: "bifrost-ksm-orml-ksm",
          },
          {
            id: "bifrost-ksm-orml-kusd",
          },
          {
            id: "bifrost-ksm-orml-movr",
          },
          {
            id: "bifrost-ksm-orml-pha",
          },
          {
            id: "bifrost-ksm-orml-rmrk",
          },
          {
            id: "bifrost-ksm-orml-zlk",
          },
        ],
        account: "*25519",
        subscanUrl: "https://bifrost.subscan.io/",
        rpcs: [
          {
            url: "wss://bifrost-rpc.liebi.com/ws",
            isHealthy: true,
          },
          {
            url: "wss://us.bifrost-rpc.liebi.com/ws",
            isHealthy: true,
          },
          {
            url: "wss://eu.bifrost-rpc.liebi.com/ws",
            isHealthy: true,
          },
          {
            url: "wss://bifrost-parachain.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://bifrost-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2001,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "bit-country-pioneer",
        isTestnet: false,
        sortIndex: 13,
        genesisHash: "0xf22b7850cdd5a7657bbfd90ac86441275bbc57ace3d2698a740c7b0ec4de5ec3",
        prefix: 268,
        name: "Bit.Country Pioneer",
        chainName: "Pioneer Network",
        implName: "pioneer-runtime",
        specName: "pioneer-runtime",
        specVersion: "6",
        nativeToken: {
          id: "bit-country-pioneer-native-neer",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://pioneer-1-rpc.bit.country",
            isHealthy: false,
          },
          {
            url: "wss://pioneer.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2096,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "calamari",
        isTestnet: false,
        sortIndex: 14,
        genesisHash: "0x4ac80c99289841dd946ef92765bf659a307d39189b3ce374a92b5f0415ee17a1",
        prefix: 42,
        name: "Calamari",
        chainName: "Calamari Parachain",
        implName: "calamari",
        specName: "calamari",
        specVersion: "3151",
        nativeToken: {
          id: "calamari-native-kma",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://calamari.subscan.io/",
        rpcs: [
          {
            url: "wss://ws.calamari.systems/",
            isHealthy: true,
          },
          {
            url: "wss://calamari.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://calamari-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2084,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "centrifuge",
        isTestnet: false,
        sortIndex: 15,
        genesisHash: "0xb3db41421702df9a7fcac62b53ffeac85f7853cc4e689e0b93aeb3db18c09d82",
        prefix: 42,
        name: "Centrifuge",
        chainName: "Centrifuge",
        implName: "centrifuge",
        specName: "centrifuge",
        specVersion: "1005",
        nativeToken: {
          id: "centrifuge-native-cfg",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://centrifuge.subscan.io/",
        rpcs: [
          {
            url: "wss://fullnode.parachain.centrifuge.io",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2031,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "clover",
        isTestnet: false,
        sortIndex: 16,
        genesisHash: "0x5c7bd13edf349b33eb175ffae85210299e324d852916336027391536e686f267",
        prefix: 42,
        name: "Clover",
        chainName: "Clover",
        implName: "clover-mainnet",
        specName: "clover-mainnet",
        specVersion: "19",
        nativeToken: {
          id: "clover-native-clv",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://clover.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc-para.clover.finance",
            isHealthy: true,
          },
          {
            url: "wss://clover.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2002,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "coinversation",
        isTestnet: false,
        sortIndex: 17,
        genesisHash: null,
        prefix: null,
        name: "Coinversation",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2027,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "composable-finance",
        isTestnet: false,
        sortIndex: 18,
        genesisHash: "0xdaab8df776eb52ec604a5df5d388bb62a050a0aaec4556a64265b9d42755552d",
        prefix: 50,
        name: "Composable Finance",
        chainName: "Composable Finance",
        implName: "composable",
        specName: "composable",
        specVersion: "1100",
        nativeToken: {
          id: "composable-finance-native-layr",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.composable.finance",
            isHealthy: true,
          },
          {
            url: "wss://composable-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2019,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "crust",
        isTestnet: false,
        sortIndex: 19,
        genesisHash: "0x8b404e7ed8789d813982b9cb4c8b664c05b3fbf433309f603af014ec9ce56a8c",
        prefix: 66,
        name: "Crust",
        chainName: "Crust",
        implName: "crustio-crust",
        specName: "crust",
        specVersion: "18",
        nativeToken: {
          id: "crust-native-cru",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://crust.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.crust.network",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2008,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "crust-shadow",
        isTestnet: false,
        sortIndex: 20,
        genesisHash: "0xd4c0c08ca49dc7c680c3dac71a7c0703e5b222f4b6c03fe4c5219bb8f22c18dc",
        prefix: 42,
        name: "Crust Shadow",
        chainName: "Crust Shadow",
        implName: "crust-collator",
        specName: "crust-collator",
        specVersion: "13",
        nativeToken: {
          id: "crust-shadow-native-csm",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://shadow.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc-shadow.crust.network/",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2012,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "darwinia",
        isTestnet: false,
        sortIndex: 21,
        genesisHash: "0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8",
        prefix: 18,
        name: "Darwinia",
        chainName: "Darwinia",
        implName: "Darwinia",
        specName: "Darwinia",
        specVersion: "1224",
        nativeToken: {
          id: "darwinia-native-ring",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://darwinia.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.darwinia.network",
            isHealthy: true,
          },
          {
            url: "wss://darwinia-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2003,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "darwinia-crab",
        isTestnet: false,
        sortIndex: 22,
        genesisHash: "0x34f61bfda344b3fad3c3e38832a91448b3c613b199eb23e5110a635d71c13c65",
        prefix: 42,
        name: "Darwinia Crab",
        chainName: "Darwinia Crab",
        implName: "Darwinia Crab",
        specName: "Crab",
        specVersion: "1224",
        nativeToken: {
          id: "darwinia-crab-native-crab",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://crab.subscan.io/",
        rpcs: [
          {
            url: "wss://crab-rpc.darwinia.network/",
            isHealthy: true,
          },
          {
            url: "wss://darwiniacrab-rpc.dwellir.com/",
            isHealthy: true,
          },
          {
            url: "wss://darwinia-crab.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2105,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "darwinia-crab-redirect",
        isTestnet: false,
        sortIndex: 23,
        genesisHash: null,
        prefix: null,
        name: "Darwinia Crab Redirect",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://crab-redirect-rpc.darwinia.network/",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2006,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "efinity",
        isTestnet: false,
        sortIndex: 24,
        genesisHash: "0x335369975fced3fc22e23498da306a712f4fd964c957364d53c49cea9db8bc2f",
        prefix: 1110,
        name: "Efinity",
        chainName: "Efinity",
        implName: "efinity",
        specName: "efinity",
        specVersion: "3",
        nativeToken: {
          id: "efinity-native-efi",
        },
        tokens: [],
        account: "Sr25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.efinity.io",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2021,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "encointer",
        isTestnet: false,
        sortIndex: 25,
        genesisHash: "0x7dd99936c1e9e6d1ce7d90eb6f33bea8393b4bf87677d675aa63c9cb3e8c5b5b",
        prefix: 2,
        name: "Encointer",
        chainName: "Encointer on Kusama",
        implName: "encointer-parachain",
        specName: "encointer-parachain",
        specVersion: "7",
        nativeToken: {
          id: "encointer-native-ksm",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api.kusama.encointer.org",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 1001,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "encointer-canary",
        isTestnet: false,
        sortIndex: 26,
        genesisHash: null,
        prefix: null,
        name: "Encointer Canary",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://canary.encointer.org",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2014,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "equilibrium",
        isTestnet: false,
        sortIndex: 27,
        genesisHash: null,
        prefix: null,
        name: "Equilibrium",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: "https://equilibrium.subscan.io/",
        rpcs: [
          {
            url: "wss://node.equilibrium.io",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2011,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "genshiro",
        isTestnet: false,
        sortIndex: 29,
        genesisHash: "0x9b8cefc0eb5c568b527998bdd76c184e2b76ae561be76e4667072230217ea243",
        prefix: 67,
        name: "Genshiro",
        chainName: "Genshiro",
        implName: "Genshiro",
        specName: "Genshiro",
        specVersion: "38",
        nativeToken: {
          id: "genshiro-native-token",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://node.genshiro.io",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2024,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "hydradx",
        isTestnet: false,
        sortIndex: 31,
        genesisHash: null,
        prefix: null,
        name: "HydraDX",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc-01.hydradx.io",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2034,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "integritee",
        isTestnet: false,
        sortIndex: 32,
        genesisHash: "0xcdedc8eadbfa209d3f207bba541e57c3c58a667b05a2e1d1e86353c9000758da",
        prefix: 13,
        name: "Integritee",
        chainName: "Integritee Network (Kusama)",
        implName: "integritee-full",
        specName: "integritee-parachain",
        specVersion: "22",
        nativeToken: {
          id: "integritee-native-teer",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://integritee.subscan.io/",
        rpcs: [
          {
            url: "wss://kusama.api.integritee.network",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2015,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "interlay",
        isTestnet: false,
        sortIndex: 33,
        genesisHash: "0xbf88efe70e9e0e916416e8bed61f2b45717f517d7f3523e33c7b001e5ffcbc72",
        prefix: 2032,
        name: "Interlay",
        chainName: "Interlay",
        implName: "interlay-parachain",
        specName: "interlay-parachain",
        specVersion: "3",
        nativeToken: {
          id: "interlay-native-intr",
        },
        tokens: [
          {
            id: "interlay-orml-dot",
          },
          {
            id: "interlay-orml-ibtc",
          },
          {
            id: "interlay-orml-intr",
          },
          {
            id: "interlay-orml-kbtc",
          },
          {
            id: "interlay-orml-kint",
          },
          {
            id: "interlay-orml-ksm",
          },
        ],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api.interlay.io/parachain",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2032,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "karura",
        isTestnet: false,
        sortIndex: 34,
        genesisHash: "0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b",
        prefix: 8,
        name: "Karura",
        chainName: "Karura",
        implName: "karura",
        specName: "karura",
        specVersion: "2070",
        nativeToken: {
          id: "karura-native-kar",
        },
        tokens: [
          {
            id: "karura-orml-bnc",
          },
          {
            id: "karura-orml-kar",
          },
          {
            id: "karura-orml-kbtc",
          },
          {
            id: "karura-orml-kint",
          },
          {
            id: "karura-orml-ksm",
          },
          {
            id: "karura-orml-kusd",
          },
          {
            id: "karura-orml-lksm",
          },
          {
            id: "karura-orml-pha",
          },
          {
            id: "karura-orml-tai",
          },
          {
            id: "karura-orml-vsksm",
          },
        ],
        account: "*25519",
        subscanUrl: "https://karura.subscan.io/",
        rpcs: [
          {
            url: "wss://karura-rpc-0.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc-1.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc-2.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc-3.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://karura.polkawallet.io",
            isHealthy: true,
          },
          {
            url: "wss://karura.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2000,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "khala",
        isTestnet: false,
        sortIndex: 35,
        genesisHash: "0xd43540ba6d3eb4897c28a77d48cb5b729fea37603cbbfc7a86a73b72adb3be8d",
        prefix: 30,
        name: "Khala",
        chainName: "Khala",
        implName: "khala",
        specName: "khala",
        specVersion: "1150",
        nativeToken: {
          id: "khala-native-pha",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://khala.subscan.io/",
        rpcs: [
          {
            url: "wss://khala-api.phala.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://khala.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://khala-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2004,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kico",
        isTestnet: false,
        sortIndex: 36,
        genesisHash: "0x52149c30c1eb11460dce6c08b73df8d53bb93b4a15d0a2e7fd5dafe86a73c0da",
        prefix: 42,
        name: "Kico",
        chainName: "KICO",
        implName: "KICO",
        specName: "KICO",
        specVersion: "1310",
        nativeToken: {
          id: "kico-native-kico",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.kico.dico.io",
            isHealthy: true,
          },
          {
            url: "wss://rpc.api.kico.dico.io",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2107,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kilt-spiritnet",
        isTestnet: false,
        sortIndex: 37,
        genesisHash: "0x411f057b9107718c9624d6aa4a3f23c1653898297f3d4d529d9bb6511a39dd21",
        prefix: 38,
        name: "KILT Spiritnet",
        chainName: "KILT Spiritnet",
        implName: "kilt-spiritnet",
        specName: "kilt-spiritnet",
        specVersion: "10620",
        nativeToken: {
          id: "kilt-spiritnet-native-kilt",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://spiritnet.subscan.io/",
        rpcs: [
          {
            url: "wss://spiritnet.kilt.io/",
            isHealthy: true,
          },
          {
            url: "wss://spiritnet.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://kilt-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2086,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kintsugi-btc",
        isTestnet: false,
        sortIndex: 38,
        genesisHash: "0x9af9a64e6e4da8e3073901c3ff0cc4c3aad9563786d89daf6ad820b6e14a0b8b",
        prefix: 2092,
        name: "Kintsugi",
        chainName: "kintsugi",
        implName: "kintsugi-parachain",
        specName: "kintsugi-parachain",
        specVersion: "17",
        nativeToken: {
          id: "kintsugi-btc-native-kint",
        },
        tokens: [
          {
            id: "kintsugi-btc-orml-dot",
          },
          {
            id: "kintsugi-btc-orml-ibtc",
          },
          {
            id: "kintsugi-btc-orml-intr",
          },
          {
            id: "kintsugi-btc-orml-kbtc",
          },
          {
            id: "kintsugi-btc-orml-kint",
          },
          {
            id: "kintsugi-btc-orml-ksm",
          },
        ],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api-kusama.interlay.io/parachain",
            isHealthy: true,
          },
          {
            url: "wss://kintsugi.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://kintsugi-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2092,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kpron",
        isTestnet: false,
        sortIndex: 39,
        genesisHash: null,
        prefix: null,
        name: "Kpron",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://kusama-kpron-rpc.apron.network/",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2019,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "litentry",
        isTestnet: false,
        sortIndex: 40,
        genesisHash: null,
        prefix: null,
        name: "Litentry",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://parachain.litentry.io",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2013,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "litmus",
        isTestnet: false,
        sortIndex: 41,
        genesisHash: "0xda5831fbc8570e3c6336d0d72b8c08f8738beefec812df21ef2afc2982ede09c",
        prefix: 131,
        name: "Litmus",
        chainName: "Litmus",
        implName: "litmus-parachain",
        specName: "litmus-parachain",
        specVersion: "9071",
        nativeToken: {
          id: "litmus-native-lit",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.litmus-parachain.litentry.io",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2106,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "loom",
        isTestnet: false,
        sortIndex: 42,
        genesisHash: null,
        prefix: null,
        name: "Loom",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2080,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "mangata",
        isTestnet: false,
        sortIndex: 43,
        genesisHash: "0xd611f22d291c5b7b69f1e105cca03352984c344c4421977efaa4cbdd1834e2aa",
        prefix: 42,
        name: "MangataX",
        chainName: "Mangata Kusama Mainnet",
        implName: "mangata-parachain",
        specName: "mangata-parachain",
        specVersion: "4",
        nativeToken: {
          id: "mangata-native-mgx",
        },
        tokens: [
          {
            id: "mangata-orml-mgx",
          },
        ],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://prod-kusama-collator-01.mangatafinance.cloud",
            isHealthy: true,
          },
          {
            url: "wss://mangata-x.api.onfinality.io/public-ws",
            isHealthy: false,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "manta",
        isTestnet: false,
        sortIndex: 44,
        genesisHash: "0x7822fe86be209e140e1bdb80fb09539d1825e3d1dfee79ce37c336a832a26d48",
        prefix: 42,
        name: "Manta",
        chainName: "Manta Parachain",
        implName: "manta",
        specName: "manta",
        specVersion: "3090",
        nativeToken: {
          id: "manta-native-manta",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://pectinata.manta.systems",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2015,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "mars",
        isTestnet: false,
        sortIndex: 45,
        genesisHash: "0x1932f141fe67eba7ad0bdfe8292f0d932bf6ce4872433f707039de2794b9a18b",
        prefix: 42,
        name: "Mars",
        chainName: "Mars",
        implName: "ares-mars",
        specName: "ares-mars",
        specVersion: "117",
        nativeToken: {
          id: "mars-native-amas",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://wss.mars.aresprotocol.io",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2008,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "moonbeam",
        isTestnet: false,
        sortIndex: 46,
        genesisHash: "0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d",
        prefix: 42,
        name: "Moonbeam",
        chainName: "Moonbeam",
        implName: "moonbeam",
        specName: "moonbeam",
        specVersion: "1504",
        nativeToken: {
          id: "moonbeam-native-glmr",
        },
        tokens: [],
        account: "secp256k1",
        subscanUrl: "https://moonbeam.subscan.io/",
        rpcs: [
          {
            url: "wss://wss.api.moonbeam.network",
            isHealthy: true,
          },
          {
            url: "wss://moonbeam.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://moonbeam-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [
          {
            id: "1284",
          },
        ],
        parathreads: [],
        paraId: 2004,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "moonriver",
        isTestnet: false,
        sortIndex: 48,
        genesisHash: "0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b",
        prefix: 42,
        name: "Moonriver",
        chainName: "Moonriver",
        implName: "moonriver",
        specName: "moonriver",
        specVersion: "1504",
        nativeToken: {
          id: "moonriver-native-movr",
        },
        tokens: [],
        account: "secp256k1",
        subscanUrl: "https://moonriver.subscan.io/",
        rpcs: [
          {
            url: "wss://wss.moonriver.moonbeam.network",
            isHealthy: true,
          },
          {
            url: "wss://moonriver.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.pinknode.io/moonriver/explorer",
            isHealthy: true,
          },
          {
            url: "wss://moonriver-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [
          {
            id: "1285",
          },
        ],
        parathreads: [],
        paraId: 2023,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "nodle",
        isTestnet: false,
        sortIndex: 50,
        genesisHash: "0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21",
        prefix: 42,
        name: "Nodle",
        chainName: "Nodle Parachain",
        implName: "nodle-para",
        specName: "nodle-para",
        specVersion: "10",
        nativeToken: {
          id: "nodle-native-nodl",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://nodle.subscan.io/",
        rpcs: [
          {
            url: "wss://nodle-parachain.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://eden-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2026,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "parallel",
        isTestnet: false,
        sortIndex: 51,
        genesisHash: "0xe61a41c53f5dcd0beb09df93b34402aada44cb05117b71059cce40a2723a4e97",
        prefix: 172,
        name: "Parallel",
        chainName: "Parallel",
        implName: "parallel",
        specName: "parallel",
        specVersion: "187",
        nativeToken: {
          id: "parallel-native-para",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://parallel.subscan.io/",
        rpcs: [
          {
            url: "wss://parallel.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.parallel.fi",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2012,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "parallel-heiko",
        isTestnet: false,
        sortIndex: 52,
        genesisHash: "0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b",
        prefix: 110,
        name: "Parallel Heiko",
        chainName: "Parallel Heiko",
        implName: "heiko",
        specName: "heiko",
        specVersion: "187",
        nativeToken: {
          id: "parallel-heiko-native-hko",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://parallel-heiko.subscan.io/",
        rpcs: [
          {
            url: "wss://parallel-heiko.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://heiko-rpc.parallel.fi",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2085,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "phala",
        isTestnet: false,
        sortIndex: 53,
        genesisHash: "0x1bb969d85965e4bb5a651abbedf21a54b6b31a21f66b5401cc3f1e286268d736",
        prefix: 30,
        name: "Phala",
        chainName: "Phala",
        implName: "phala",
        specName: "phala",
        specVersion: "1151",
        nativeToken: {
          id: "phala-native-pha",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api.phala.network/ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2035,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "picasso",
        isTestnet: false,
        sortIndex: 54,
        genesisHash: "0x6811a339673c9daa897944dcdac99c6e2939cc88245ed21951a0a3c9a2be75bc",
        prefix: 49,
        name: "Picasso",
        chainName: "Picasso",
        implName: "picasso",
        specName: "picasso",
        specVersion: "1200",
        nativeToken: {
          id: "picasso-native-pica",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://picasso-rpc.composable.finance",
            isHealthy: true,
          },
          {
            url: "wss://picasso-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2087,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "pichiu",
        isTestnet: false,
        sortIndex: 55,
        genesisHash: "0x0e06260459b4f9034aba0a75108c08ed73ea51d2763562749b1d3600986c4ea5",
        prefix: 42,
        name: "Pichiu",
        chainName: "Pichiu Network",
        implName: "pichiu",
        specName: "pichiu",
        specVersion: "14",
        nativeToken: {
          id: "pichiu-native-pchu",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://kusama.kylin-node.co.uk",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2102,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "polkadex",
        isTestnet: false,
        sortIndex: 56,
        genesisHash: "0x3920bcb4960a1eef5580cd5367ff3f430eef052774f78468852f7b9cb39f8a3c",
        prefix: 88,
        name: "Polkadex",
        chainName: "Polkadex Main Network",
        implName: "polkadex-official",
        specName: "node",
        specVersion: "276",
        nativeToken: {
          id: "polkadex-native-pdex",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://polkadex.subscan.io/",
        rpcs: [
          {
            url: "wss://mainnet.polkadex.trade/",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2040,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "polkasmith",
        isTestnet: false,
        sortIndex: 57,
        genesisHash: null,
        prefix: null,
        name: "PolkaSmith",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2009,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "quartz",
        isTestnet: false,
        sortIndex: 59,
        genesisHash: "0xcd4d732201ebe5d6b014edda071c4203e16867305332301dc8d092044b28e554",
        prefix: 255,
        name: "Quartz",
        chainName: "QUARTZ by UNIQUE",
        implName: "quartz",
        specName: "quartz",
        specVersion: "921000",
        nativeToken: {
          id: "quartz-native-qtz",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://quartz.subscan.io/",
        rpcs: [
          {
            url: "wss://quartz.unique.network",
            isHealthy: true,
          },
          {
            url: "wss://quartz.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://eu-ws-quartz.unique.network",
            isHealthy: true,
          },
          {
            url: "wss://us-ws-quartz.unique.network",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2095,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "robonomics",
        isTestnet: false,
        sortIndex: 60,
        genesisHash: "0x631ccc82a078481584041656af292834e1ae6daab61d2875b4dd0c14bb9b17bc",
        prefix: 32,
        name: "Robonomics",
        chainName: "Robonomics",
        implName: "robonomics-airalab",
        specName: "robonomics",
        specVersion: "20",
        nativeToken: {
          id: "robonomics-native-xrt",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://robonomics.subscan.io/",
        rpcs: [
          {
            url: "wss://kusama.rpc.robonomics.network/",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2048,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "sakura",
        isTestnet: false,
        sortIndex: 61,
        genesisHash: null,
        prefix: null,
        name: "Sakura",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: "https://sakura.subscan.io/",
        rpcs: [
          {
            url: "wss://api-sakura.clover.finance",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2016,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "sherpax",
        isTestnet: false,
        sortIndex: 62,
        genesisHash: null,
        prefix: null,
        name: "SherpaX",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://sherpax.chainx.org",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2013,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "shiden",
        isTestnet: false,
        sortIndex: 63,
        genesisHash: "0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108",
        prefix: 5,
        name: "Shiden",
        chainName: "Shiden",
        implName: "shiden",
        specName: "shiden",
        specVersion: "53",
        nativeToken: {
          id: "shiden-native-sdn",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://shiden.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.shiden.astar.network",
            isHealthy: true,
          },
          {
            url: "wss://shiden.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.pinknode.io/shiden/explorer",
            isHealthy: true,
          },
          {
            url: "wss://shiden-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [
          {
            id: "336",
          },
        ],
        parathreads: [],
        paraId: 2007,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "sora-kusama",
        isTestnet: false,
        sortIndex: 65,
        genesisHash: null,
        prefix: null,
        name: "Sora Kusama",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: "https://sora.subscan.io/",
        rpcs: [
          {
            url: "wss://ws.parachain-collator-1.c1.sora2.soramitsu.co.jp",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2011,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "statemine",
        isTestnet: false,
        sortIndex: 66,
        genesisHash: "0x48239ef607d7928874027a43a67689209727dfb3d3dc5e5b03a39bdc2eda771a",
        prefix: 2,
        name: "Statemine",
        chainName: "Statemine",
        implName: "statemine",
        specName: "statemine",
        specVersion: "900",
        nativeToken: {
          id: "statemine-native-ksm",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://statemine.subscan.io/",
        rpcs: [
          {
            url: "wss://statemine-rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://statemine.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://statemine-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 1000,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "statemint",
        isTestnet: false,
        sortIndex: 67,
        genesisHash: "0x68d56f15f85d3136970ec16946040bc1752654e906147f7e43e9d539d7c3de2f",
        prefix: 42,
        name: "Statemint",
        chainName: "Statemint",
        implName: "statemint",
        specName: "statemint",
        specVersion: "900",
        nativeToken: {
          id: "statemint-native-dot",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://statemint-rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://statemint.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://statemint-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 1000,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "subdao",
        isTestnet: false,
        sortIndex: 68,
        genesisHash: null,
        prefix: null,
        name: "SubDAO",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2018,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "subgame",
        isTestnet: false,
        sortIndex: 69,
        genesisHash: "0x01cf4dbc973387c70f4db8fad8551f71faf191d9f08044d37fc617b30ffae8b9",
        prefix: 27,
        name: "SubGame",
        chainName: "SubGame",
        implName: "subgame",
        specName: "subgame",
        specVersion: "174",
        nativeToken: {
          id: "subgame-native-sgb",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://subgame.subscan.io/",
        rpcs: [
          {
            url: "wss://mainnet.subgame.org/",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2017,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "subgame-gamma",
        isTestnet: false,
        sortIndex: 70,
        genesisHash: "0x6584d9fcd3c350fd2b17e0118547c1ea54960b925d6c3255a78ac77aeeca9d04",
        prefix: 27,
        name: "SubGame Gamma",
        chainName: "Subgame Gamma",
        implName: "subgame",
        specName: "subgame",
        specVersion: "1",
        nativeToken: {
          id: "subgame-gamma-native-gsgb",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://gamma.subgame.org/",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2018,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "subsocial",
        isTestnet: false,
        sortIndex: 71,
        genesisHash: "0x0bd72c1c305172e1275278aaeb3f161e02eccb7a819e63f62d47bd53a28189f8",
        prefix: 28,
        name: "Subsocial",
        chainName: "Subsocial",
        implName: "dappforce-subsocial",
        specName: "subsocial",
        specVersion: "18",
        nativeToken: {
          id: "subsocial-native-sub",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.subsocial.network",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "subsocialx",
        isTestnet: false,
        sortIndex: 72,
        genesisHash: null,
        prefix: null,
        name: "SubsocialX",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://para.subsocial.network",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2100,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "turing",
        isTestnet: false,
        sortIndex: 73,
        genesisHash: "0x0f62b701fb12d02237a33b84818c11f621653d2b1614c777973babf4652b535d",
        prefix: 51,
        name: "Turing",
        chainName: "Turing Network",
        implName: "turing",
        specName: "turing",
        specVersion: "282",
        nativeToken: {
          id: "turing-native-tur",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.turing.oak.tech",
            isHealthy: true,
          },
          {
            url: "wss://turing.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2114,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "unorthodox",
        isTestnet: false,
        sortIndex: 74,
        genesisHash: null,
        prefix: null,
        name: "Unorthodox",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.kusama.standard.tech",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: 2094,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "zeitgeist",
        isTestnet: false,
        sortIndex: 75,
        genesisHash: "0x1bf2a2ecb4a868de66ea8610f2ce7c8c43706561b6476031315f6640fe38e060",
        prefix: 73,
        name: "Zeitgeist",
        chainName: "Zeitgeist",
        implName: "zeitgeist",
        specName: "zeitgeist",
        specVersion: "36",
        nativeToken: {
          id: "zeitgeist-native-ztg",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc-0.zeitgeist.pm",
            isHealthy: true,
          },
          {
            url: "wss://zeitgeist-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: 2101,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "aleph-zero-testnet",
        isTestnet: true,
        sortIndex: 76,
        genesisHash: "0x05d5279c52c484cc80396535a316add7d47b1c5b9e0398dd1f584149341460c5",
        prefix: 42,
        name: "Aleph Zero Testnet",
        chainName: "Aleph Zero Testnet",
        implName: "aleph-node",
        specName: "aleph-node",
        specVersion: "12",
        nativeToken: {
          id: "aleph-zero-testnet-native-tzero",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://ws.test.azero.dev",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "dolphin",
        isTestnet: true,
        sortIndex: 77,
        genesisHash: null,
        prefix: null,
        name: "Dolphin Testnet",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: "https://dolphin.subscan.io/",
        rpcs: [
          {
            url: "wss://trillian.dolphin.red/",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "gm-rococo",
        isTestnet: true,
        sortIndex: 78,
        genesisHash: null,
        prefix: null,
        name: "GM Parachain Rococo",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rococo.gmordie.com",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "mandala",
        isTestnet: true,
        sortIndex: 81,
        genesisHash: "0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b",
        prefix: 42,
        name: "Mandala",
        chainName: "Acala Mandala TC7",
        implName: "mandala",
        specName: "mandala",
        specVersion: "2064",
        nativeToken: {
          id: "mandala-native-aca",
        },
        tokens: [
          {
            id: "mandala-orml-aca",
          },
          {
            id: "mandala-orml-ausd",
          },
          {
            id: "mandala-orml-bnc",
          },
          {
            id: "mandala-orml-cash",
          },
          {
            id: "mandala-orml-dot",
          },
          {
            id: "mandala-orml-kar",
          },
          {
            id: "mandala-orml-kbtc",
          },
          {
            id: "mandala-orml-kint",
          },
          {
            id: "mandala-orml-ksm",
          },
          {
            id: "mandala-orml-kusd",
          },
          {
            id: "mandala-orml-ldot",
          },
          {
            id: "mandala-orml-lksm",
          },
          {
            id: "mandala-orml-pha",
          },
          {
            id: "mandala-orml-renbtc",
          },
          {
            id: "mandala-orml-tai",
          },
          {
            id: "mandala-orml-vsksm",
          },
        ],
        account: "*25519",
        subscanUrl: "https://acala-testnet.subscan.io/",
        rpcs: [
          {
            url: "wss://mandala.polkawallet.io",
            isHealthy: false,
          },
          {
            url: "wss://acala-mandala.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [
          {
            id: "595",
          },
        ],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "mangata-testnet",
        isTestnet: true,
        sortIndex: 83,
        genesisHash: null,
        prefix: null,
        name: "Mangata Testnet",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://v4-prod-collator-01.mangatafinance.cloud",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "moonbase",
        isTestnet: true,
        sortIndex: 84,
        genesisHash: "0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527",
        prefix: 42,
        name: "Moonbase Alpha",
        chainName: "Moonbase Alpha",
        implName: "moonbase",
        specName: "moonbase",
        specVersion: "1605",
        nativeToken: {
          id: "moonbase-native-dev",
        },
        tokens: [],
        account: "secp256k1",
        subscanUrl: "https://moonbase.subscan.io/",
        rpcs: [
          {
            url: "wss://moonbeam-alpha.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [
          {
            id: "1287",
          },
        ],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "neumann",
        isTestnet: true,
        sortIndex: 86,
        genesisHash: "0x42e75532d6809775cef4b9ca8e4bb49be2dc1e87c9ff1ba299e78481b5cb3047",
        prefix: 51,
        name: "Neumann",
        chainName: "Neumann Network",
        implName: "neumann",
        specName: "neumann",
        specVersion: "281",
        nativeToken: {
          id: "neumann-native-neu",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://neumann.api.onfinality.io/public-ws",
            isHealthy: false,
          },
          {
            url: "wss://rpc.testnet.oak.tech",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "shibuya",
        isTestnet: true,
        sortIndex: 89,
        genesisHash: "0xddb89973361a170839f80f152d2e9e38a376a5a7eccefcade763f46a8e567019",
        prefix: 5,
        name: "Shibuya Testnet",
        chainName: "Shibuya Testnet",
        implName: "shibuya",
        specName: "shibuya",
        specVersion: "54",
        nativeToken: {
          id: "shibuya-native-sby",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://shibuya.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.shibuya.astar.network",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [
          {
            id: "81",
          },
        ],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "westend",
        isTestnet: true,
        sortIndex: 91,
        genesisHash: "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e",
        prefix: 42,
        name: "Westend",
        chainName: "Westend",
        implName: "parity-westend",
        specName: "westend",
        specVersion: "9230",
        nativeToken: {
          id: "westend-native-wnd",
        },
        tokens: [],
        account: "*25519",
        subscanUrl: "https://westend.subscan.io/",
        rpcs: [
          {
            url: "wss://westend-rpc.polkadot.io",
            isHealthy: true,
          },
        ],
        isHealthy: true,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "zero-io",
        isTestnet: true,
        sortIndex: 92,
        genesisHash: null,
        prefix: null,
        name: "Zero.io",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: null,
        tokens: [],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://alphaville.zero.io/",
            isHealthy: false,
          },
        ],
        isHealthy: false,
        evmNetworks: [],
        parathreads: [],
        paraId: null,
        relay: null,
      },
    ],
  },
}

export const getChains = jest.fn(() => Promise.resolve(mock.data?.chains || []))
