/*
// When changes to the data expected from the chains gql endpoint are made, please update the following object by copying and pasting the data from 
// @core/domains/chains/api.graphqlUrl with the query given at @core/domains/chains/api.chaindataQuery
*/
const data = {
  data: {
    chains: [
      {
        id: "polkadot",
        sortIndex: 0,
        isTestnet: false,
        genesisHash: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
        prefix: 0,
        name: "Polkadot",
        chainName: "Polkadot",
        implName: "parity-polkadot",
        specName: "polkadot",
        specVersion: "9190",
        nativeToken: {
          id: "polkadot-native-DOT",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://polkadot.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://polkadot-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [
          {
            id: "statemint",
            paraId: 1000,
          },
          {
            id: "acala",
            paraId: 2000,
          },
          {
            id: "bifrost-dot",
            paraId: 2001,
          },
          {
            id: "clover",
            paraId: 2002,
          },
          {
            id: "darwinia",
            paraId: 2003,
          },
          {
            id: "moonbeam",
            paraId: 2004,
          },
          {
            id: "astar",
            paraId: 2006,
          },
          {
            id: "crust",
            paraId: 2008,
          },
          {
            id: "equilibrium",
            paraId: 2011,
          },
          {
            id: "parallel",
            paraId: 2012,
          },
          {
            id: "litentry",
            paraId: 2013,
          },
          {
            id: "manta",
            paraId: 2015,
          },
          {
            id: "subgame",
            paraId: 2017,
          },
          {
            id: "subdao",
            paraId: 2018,
          },
          {
            id: "composable-finance",
            paraId: 2019,
          },
          {
            id: "efinity",
            paraId: 2021,
          },
          {
            id: "nodle",
            paraId: 2026,
          },
          {
            id: "coinversation",
            paraId: 2027,
          },
          {
            id: "ares",
            paraId: 2028,
          },
          {
            id: "centrifuge",
            paraId: 2031,
          },
          {
            id: "interlay",
            paraId: 2032,
          },
          {
            id: "hydradx",
            paraId: 2034,
          },
          {
            id: "phala",
            paraId: 2035,
          },
          {
            id: "polkadex",
            paraId: 2040,
          },
        ],
        paraId: null,
        relay: null,
      },
      {
        id: "kusama",
        sortIndex: 1,
        isTestnet: false,
        genesisHash: "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe",
        prefix: 2,
        name: "Kusama",
        chainName: "Kusama",
        implName: "parity-kusama",
        specName: "kusama",
        specVersion: "9200",
        nativeToken: {
          id: "kusama-native-KSM",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://kusama.subscan.io/",
        rpcs: [
          {
            url: "wss://kusama-rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://kusama-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [
          {
            id: "statemine",
            paraId: 1000,
          },
          {
            id: "encointer",
            paraId: 1001,
          },
          {
            id: "karura",
            paraId: 2000,
          },
          {
            id: "bifrost-ksm",
            paraId: 2001,
          },
          {
            id: "khala",
            paraId: 2004,
          },
          {
            id: "darwinia-crab-redirect",
            paraId: 2006,
          },
          {
            id: "shiden",
            paraId: 2007,
          },
          {
            id: "mars",
            paraId: 2008,
          },
          {
            id: "polkasmith",
            paraId: 2009,
          },
          {
            id: "sora-kusama",
            paraId: 2011,
          },
          {
            id: "crust-shadow",
            paraId: 2012,
          },
          {
            id: "sherpax",
            paraId: 2013,
          },
          {
            id: "encointer-canary",
            paraId: 2014,
          },
          {
            id: "integritee",
            paraId: 2015,
          },
          {
            id: "sakura",
            paraId: 2016,
          },
          {
            id: "subgame-gamma",
            paraId: 2018,
          },
          {
            id: "kpron",
            paraId: 2019,
          },
          {
            id: "moonriver",
            paraId: 2023,
          },
          {
            id: "genshiro",
            paraId: 2024,
          },
          {
            id: "robonomics",
            paraId: 2048,
          },
          {
            id: "loom",
            paraId: 2080,
          },
          {
            id: "calamari",
            paraId: 2084,
          },
          {
            id: "parallel-heiko",
            paraId: 2085,
          },
          {
            id: "kilt-spiritnet",
            paraId: 2086,
          },
          {
            id: "picasso",
            paraId: 2087,
          },
          {
            id: "altair",
            paraId: 2088,
          },
          {
            id: "basilisk",
            paraId: 2090,
          },
          {
            id: "kintsugi-btc",
            paraId: 2092,
          },
          {
            id: "unorthodox",
            paraId: 2094,
          },
          {
            id: "quartz",
            paraId: 2095,
          },
          {
            id: "bit-country-pioneer",
            paraId: 2096,
          },
          {
            id: "subsocialx",
            paraId: 2100,
          },
          {
            id: "zeitgeist",
            paraId: 2101,
          },
          {
            id: "pichiu",
            paraId: 2102,
          },
          {
            id: "darwinia-crab",
            paraId: 2105,
          },
          {
            id: "litmus",
            paraId: 2106,
          },
          {
            id: "kico",
            paraId: 2107,
          },
          {
            id: "turing",
            paraId: 2114,
          },
        ],
        paraId: null,
        relay: null,
      },
      {
        id: "acala",
        sortIndex: 2,
        isTestnet: false,
        genesisHash: "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c",
        prefix: 10,
        name: "Acala",
        chainName: "Acala",
        implName: "acala",
        specName: "acala",
        specVersion: "2060",
        nativeToken: {
          id: "acala-native-ACA",
        },
        tokensCurrencyIdIndex: 0,
        tokens: [
          {
            id: "acala-orml-ACA",
          },
          {
            id: "acala-orml-AUSD",
          },
          {
            id: "acala-orml-DOT",
          },
          {
            id: "acala-orml-LDOT",
          },
        ],
        account: "*25519",
        subscanUrl: "https://acala.subscan.io/",
        rpcs: [
          {
            url: "wss://acala-rpc-0.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc-1.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc-2.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc-3.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://acala.polkawallet.io",
            isHealthy: true,
          },
          {
            url: "wss://acala-polkadot.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://acala-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2000,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "altair",
        sortIndex: 3,
        isTestnet: false,
        genesisHash: "0xaa3876c1dc8a1afcc2e9a685a49ff7704cfd36ad8c90bf2702b9d1b00cc40011",
        prefix: 136,
        name: "Altair",
        chainName: "Altair",
        implName: "altair",
        specName: "altair",
        specVersion: "1011",
        nativeToken: {
          id: "altair-native-AIR",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://altair.subscan.io/",
        rpcs: [
          {
            url: "wss://fullnode.altair.centrifuge.io",
            isHealthy: true,
          },
          {
            url: "wss://altair.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2088,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "ares",
        sortIndex: 4,
        isTestnet: false,
        genesisHash: "0x52097bd7416205228bf13ac3eda6f16de56c19cac3476866b8b8a9c00d515870",
        prefix: 34,
        name: "Ares",
        chainName: "Odyssey",
        implName: "ares-odyssey",
        specName: "ares-odyssey",
        specVersion: "117",
        nativeToken: {
          id: "ares-native-AMAS",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://wss.odyssey.aresprotocol.io",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2028,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "astar",
        sortIndex: 5,
        isTestnet: false,
        genesisHash: "0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6",
        prefix: 5,
        name: "Astar",
        chainName: "Astar",
        implName: "astar",
        specName: "astar",
        specVersion: "15",
        nativeToken: {
          id: "astar-native-ASTR",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://astar.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.astar.network",
            isHealthy: true,
          },
          {
            url: "wss://astar.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://astar-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: "https://blockscout.com/astar",
        ethereumRpcs: [
          {
            url: "https://evm.astar.network",
            isHealthy: true,
          },
          {
            url: "https://astar.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "https://astar-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumId: 592,
        isHealthy: true,
        parathreads: [],
        paraId: 2006,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "basilisk",
        sortIndex: 6,
        isTestnet: false,
        genesisHash: "0xa85cfb9b9fd4d622a5b28289a02347af987d8f73fa3108450e2b4a11c1ce5755",
        prefix: 10041,
        name: "Basilisk",
        chainName: "Basilisk",
        implName: "basilisk",
        specName: "basilisk",
        specVersion: "43",
        nativeToken: {
          id: "basilisk-native-BSX",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc-01.basilisk.hydradx.io",
            isHealthy: false,
          },
          {
            url: "wss://basilisk.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://basilisk-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2090,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "bifrost-dot",
        sortIndex: 7,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Bifrost",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "bifrost-dot-native-undefined",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://bifrost-dot.liebi.com/ws",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2001,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "bifrost-ksm",
        sortIndex: 8,
        isTestnet: false,
        genesisHash: "0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed",
        prefix: 6,
        name: "Bifrost",
        chainName: "Bifrost",
        implName: "bifrost",
        specName: "bifrost",
        specVersion: "942",
        nativeToken: {
          id: "bifrost-ksm-native-BNC",
        },
        tokensCurrencyIdIndex: 2,
        tokens: [
          {
            id: "bifrost-ksm-orml-BNC",
          },
          {
            id: "bifrost-ksm-orml-KUSD",
          },
          {
            id: "bifrost-ksm-orml-DOT",
          },
          {
            id: "bifrost-ksm-orml-KSM",
          },
          {
            id: "bifrost-ksm-orml-KAR",
          },
          {
            id: "bifrost-ksm-orml-ZLK",
          },
          {
            id: "bifrost-ksm-orml-PHA",
          },
          {
            id: "bifrost-ksm-orml-RMRK",
          },
          {
            id: "bifrost-ksm-orml-MOVR",
          },
        ],
        account: "*25519",
        subscanUrl: "https://bifrost.subscan.io/",
        rpcs: [
          {
            url: "wss://bifrost-rpc.liebi.com/ws",
            isHealthy: true,
          },
          {
            url: "wss://us.bifrost-rpc.liebi.com/ws",
            isHealthy: true,
          },
          {
            url: "wss://eu.bifrost-rpc.liebi.com/ws",
            isHealthy: true,
          },
          {
            url: "wss://bifrost-parachain.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://bifrost-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2001,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "bit-country-pioneer",
        sortIndex: 9,
        isTestnet: false,
        genesisHash: "0xf22b7850cdd5a7657bbfd90ac86441275bbc57ace3d2698a740c7b0ec4de5ec3",
        prefix: 268,
        name: "Bit.Country Pioneer",
        chainName: "Pioneer Network",
        implName: "pioneer-runtime",
        specName: "pioneer-runtime",
        specVersion: "6",
        nativeToken: {
          id: "bit-country-pioneer-native-NEER",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://pioneer-1-rpc.bit.country",
            isHealthy: true,
          },
          {
            url: "wss://pioneer.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2096,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "calamari",
        sortIndex: 10,
        isTestnet: false,
        genesisHash: "0x4ac80c99289841dd946ef92765bf659a307d39189b3ce374a92b5f0415ee17a1",
        prefix: 78,
        name: "Calamari",
        chainName: "Calamari Parachain",
        implName: "calamari",
        specName: "calamari",
        specVersion: "3151",
        nativeToken: {
          id: "calamari-native-KMA",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://calamari.subscan.io/",
        rpcs: [
          {
            url: "wss://ws.calamari.systems/",
            isHealthy: true,
          },
          {
            url: "wss://calamari.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://calamari-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2084,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "centrifuge",
        sortIndex: 11,
        isTestnet: false,
        genesisHash: "0xb3db41421702df9a7fcac62b53ffeac85f7853cc4e689e0b93aeb3db18c09d82",
        prefix: 36,
        name: "Centrifuge",
        chainName: "Centrifuge",
        implName: "centrifuge",
        specName: "centrifuge",
        specVersion: "1005",
        nativeToken: {
          id: "centrifuge-native-CFG",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://centrifuge.subscan.io/",
        rpcs: [
          {
            url: "wss://fullnode.parachain.centrifuge.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2031,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "clover",
        sortIndex: 12,
        isTestnet: false,
        genesisHash: "0x5c7bd13edf349b33eb175ffae85210299e324d852916336027391536e686f267",
        prefix: 128,
        name: "Clover",
        chainName: "Clover",
        implName: "clover-mainnet",
        specName: "clover-mainnet",
        specVersion: "19",
        nativeToken: {
          id: "clover-native-CLV",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://clover.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc-para.clover.finance",
            isHealthy: true,
          },
          {
            url: "wss://clover.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2002,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "coinversation",
        sortIndex: 13,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Coinversation",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "coinversation-native-CTO",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.coinversation.io/",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2027,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "composable-finance",
        sortIndex: 14,
        isTestnet: false,
        genesisHash: "0xdaab8df776eb52ec604a5df5d388bb62a050a0aaec4556a64265b9d42755552d",
        prefix: 50,
        name: "Composable Finance",
        chainName: "Composable Finance",
        implName: "composable",
        specName: "composable",
        specVersion: "100",
        nativeToken: {
          id: "composable-finance-native-LAYR",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.composable.finance",
            isHealthy: true,
          },
          {
            url: "wss://composable-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2019,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "crust",
        sortIndex: 15,
        isTestnet: false,
        genesisHash: "0x8b404e7ed8789d813982b9cb4c8b664c05b3fbf433309f603af014ec9ce56a8c",
        prefix: 66,
        name: "Crust",
        chainName: "Crust",
        implName: "crustio-crust",
        specName: "crust",
        specVersion: "18",
        nativeToken: {
          id: "crust-native-CRU",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://crust.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.crust.network",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2008,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "crust-shadow",
        sortIndex: 16,
        isTestnet: false,
        genesisHash: "0xd4c0c08ca49dc7c680c3dac71a7c0703e5b222f4b6c03fe4c5219bb8f22c18dc",
        prefix: 42,
        name: "Crust Shadow",
        chainName: "Crust Shadow",
        implName: "crust-collator",
        specName: "crust-collator",
        specVersion: "12",
        nativeToken: {
          id: "crust-shadow-native-CSM",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://shadow.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc-shadow.crust.network/",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2012,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "darwinia",
        sortIndex: 17,
        isTestnet: false,
        genesisHash: "0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8",
        prefix: 18,
        name: "Darwinia",
        chainName: "Darwinia",
        implName: "Darwinia",
        specName: "Darwinia",
        specVersion: "1210",
        nativeToken: {
          id: "darwinia-native-RING",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://darwinia.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.darwinia.network",
            isHealthy: true,
          },
          {
            url: "wss://darwinia-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2003,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "darwinia-crab",
        sortIndex: 18,
        isTestnet: false,
        genesisHash: "0x34f61bfda344b3fad3c3e38832a91448b3c613b199eb23e5110a635d71c13c65",
        prefix: 42,
        name: "Darwinia Crab",
        chainName: "Darwinia Crab",
        implName: "Darwinia Crab",
        specName: "Crab",
        specVersion: "1210",
        nativeToken: {
          id: "darwinia-crab-native-CRAB",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://crab.subscan.io/",
        rpcs: [
          {
            url: "wss://crab-rpc.darwinia.network/",
            isHealthy: true,
          },
          {
            url: "wss://darwiniacrab-rpc.dwellir.com/",
            isHealthy: true,
          },
          {
            url: "wss://darwinia-crab.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2105,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "darwinia-crab-redirect",
        sortIndex: 19,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Darwinia Crab Redirect",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "darwinia-crab-redirect-native-CRING",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://crab-redirect-rpc.darwinia.network/",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2006,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "efinity",
        sortIndex: 20,
        isTestnet: false,
        genesisHash: "0x335369975fced3fc22e23498da306a712f4fd964c957364d53c49cea9db8bc2f",
        prefix: 1110,
        name: "Efinity",
        chainName: "Efinity",
        implName: "efinity",
        specName: "efinity",
        specVersion: "2",
        nativeToken: {
          id: "efinity-native-EFI",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "Sr25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.efinity.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2021,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "encointer",
        sortIndex: 21,
        isTestnet: false,
        genesisHash: "0x7dd99936c1e9e6d1ce7d90eb6f33bea8393b4bf87677d675aa63c9cb3e8c5b5b",
        prefix: 2,
        name: "Encointer",
        chainName: "Encointer on Kusama",
        implName: "encointer-parachain",
        specName: "encointer-parachain",
        specVersion: "7",
        nativeToken: {
          id: "encointer-native-KSM",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api.kusama.encointer.org",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 1001,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "encointer-canary",
        sortIndex: 22,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Encointer Canary",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "encointer-canary-native-undefined",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://canary.encointer.org",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2014,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "equilibrium",
        sortIndex: 23,
        isTestnet: false,
        genesisHash: "0x6f1a800de3daff7f5e037ddf66ab22ce03ab91874debeddb1086f5f7dbd48925",
        prefix: 68,
        name: "Equilibrium",
        chainName: "Equilibrium",
        implName: "Equilibrium",
        specName: "Equilibrium",
        specVersion: "264",
        nativeToken: {
          id: "equilibrium-native-Unknown",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://equilibrium.subscan.io/",
        rpcs: [
          {
            url: "wss://node.equilibrium.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2011,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "genshiro",
        sortIndex: 24,
        isTestnet: false,
        genesisHash: "0x9b8cefc0eb5c568b527998bdd76c184e2b76ae561be76e4667072230217ea243",
        prefix: 67,
        name: "Genshiro",
        chainName: "Genshiro",
        implName: "Genshiro",
        specName: "Genshiro",
        specVersion: "30",
        nativeToken: {
          id: "genshiro-native-TOKEN",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://node.genshiro.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2024,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "hydradx",
        sortIndex: 25,
        isTestnet: false,
        genesisHash: null,
        prefix: 63,
        name: "HydraDX",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "hydradx-native-HDX",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc-01.hydradx.io",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2034,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "integritee",
        sortIndex: 26,
        isTestnet: false,
        genesisHash: "0xcdedc8eadbfa209d3f207bba541e57c3c58a667b05a2e1d1e86353c9000758da",
        prefix: 13,
        name: "Integritee",
        chainName: "Integritee Network (Kusama)",
        implName: "integritee-full",
        specName: "integritee-parachain",
        specVersion: "18",
        nativeToken: {
          id: "integritee-native-TEER",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://integritee.subscan.io/",
        rpcs: [
          {
            url: "wss://kusama.api.integritee.network",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2015,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "interlay",
        sortIndex: 27,
        isTestnet: false,
        genesisHash: "0xbf88efe70e9e0e916416e8bed61f2b45717f517d7f3523e33c7b001e5ffcbc72",
        prefix: 2032,
        name: "Interlay",
        chainName: "Interlay",
        implName: "interlay-parachain",
        specName: "interlay-parachain",
        specVersion: "2",
        nativeToken: {
          id: "interlay-native-INTR",
        },
        tokensCurrencyIdIndex: 0,
        tokens: [
          {
            id: "interlay-orml-DOT",
          },
          {
            id: "interlay-orml-INTR",
          },
          {
            id: "interlay-orml-KSM",
          },
          {
            id: "interlay-orml-KBTC",
          },
          {
            id: "interlay-orml-KINT",
          },
        ],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api.interlay.io/parachain",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2032,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "karura",
        sortIndex: 28,
        isTestnet: false,
        genesisHash: "0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b",
        prefix: 8,
        name: "Karura",
        chainName: "Karura",
        implName: "karura",
        specName: "karura",
        specVersion: "2061",
        nativeToken: {
          id: "karura-native-KAR",
        },
        tokensCurrencyIdIndex: 0,
        tokens: [
          {
            id: "karura-orml-KAR",
          },
          {
            id: "karura-orml-KUSD",
          },
          {
            id: "karura-orml-KSM",
          },
          {
            id: "karura-orml-LKSM",
          },
          {
            id: "karura-orml-TAI",
          },
          {
            id: "karura-orml-BNC",
          },
          {
            id: "karura-orml-VSKSM",
          },
          {
            id: "karura-orml-PHA",
          },
          {
            id: "karura-orml-KINT",
          },
          {
            id: "karura-orml-KBTC",
          },
        ],
        account: "*25519",
        subscanUrl: "https://karura.subscan.io/",
        rpcs: [
          {
            url: "wss://karura-rpc-0.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc-1.aca-api.network",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc-2.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc-3.aca-api.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://karura.polkawallet.io",
            isHealthy: true,
          },
          {
            url: "wss://karura.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://karura-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2000,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "khala",
        sortIndex: 29,
        isTestnet: false,
        genesisHash: "0xd43540ba6d3eb4897c28a77d48cb5b729fea37603cbbfc7a86a73b72adb3be8d",
        prefix: 30,
        name: "Khala",
        chainName: "Khala",
        implName: "khala",
        specName: "khala",
        specVersion: "1140",
        nativeToken: {
          id: "khala-native-PHA",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://khala.subscan.io/",
        rpcs: [
          {
            url: "wss://khala-api.phala.network/ws",
            isHealthy: true,
          },
          {
            url: "wss://khala.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://khala-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2004,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kico",
        sortIndex: 30,
        isTestnet: false,
        genesisHash: "0x52149c30c1eb11460dce6c08b73df8d53bb93b4a15d0a2e7fd5dafe86a73c0da",
        prefix: 42,
        name: "Kico",
        chainName: "KICO",
        implName: "KICO",
        specName: "KICO",
        specVersion: "1310",
        nativeToken: {
          id: "kico-native-KICO",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.kico.dico.io",
            isHealthy: true,
          },
          {
            url: "wss://rpc.api.kico.dico.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2107,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kilt-spiritnet",
        sortIndex: 31,
        isTestnet: false,
        genesisHash: "0x411f057b9107718c9624d6aa4a3f23c1653898297f3d4d529d9bb6511a39dd21",
        prefix: 38,
        name: "KILT Spiritnet",
        chainName: "KILT Spiritnet",
        implName: "kilt-spiritnet",
        specName: "kilt-spiritnet",
        specVersion: "10620",
        nativeToken: {
          id: "kilt-spiritnet-native-KILT",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://spiritnet.subscan.io/",
        rpcs: [
          {
            url: "wss://spiritnet.kilt.io/",
            isHealthy: true,
          },
          {
            url: "wss://spiritnet.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://kilt-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2086,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kintsugi-btc",
        sortIndex: 32,
        isTestnet: false,
        genesisHash: "0x9af9a64e6e4da8e3073901c3ff0cc4c3aad9563786d89daf6ad820b6e14a0b8b",
        prefix: 2092,
        name: "Kintsugi",
        chainName: "kintsugi",
        implName: "kintsugi-parachain",
        specName: "kintsugi-parachain",
        specVersion: "15",
        nativeToken: {
          id: "kintsugi-btc-native-KINT",
        },
        tokensCurrencyIdIndex: 0,
        tokens: [
          {
            id: "kintsugi-btc-orml-DOT",
          },
          {
            id: "kintsugi-btc-orml-INTR",
          },
          {
            id: "kintsugi-btc-orml-KSM",
          },
          {
            id: "kintsugi-btc-orml-KBTC",
          },
          {
            id: "kintsugi-btc-orml-KINT",
          },
        ],
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api-kusama.interlay.io/parachain",
            isHealthy: true,
          },
          {
            url: "wss://kintsugi.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://kintsugi-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2092,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "kpron",
        sortIndex: 33,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Kpron",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "kpron-native-KPN",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://kusama-kpron-rpc.apron.network/",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2019,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "litentry",
        sortIndex: 34,
        isTestnet: false,
        genesisHash: null,
        prefix: 31,
        name: "Litentry",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "litentry-native-LIT",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://parachain.litentry.io",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2013,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "litmus",
        sortIndex: 35,
        isTestnet: false,
        genesisHash: "0xda5831fbc8570e3c6336d0d72b8c08f8738beefec812df21ef2afc2982ede09c",
        prefix: 131,
        name: "Litmus",
        chainName: "Litmus",
        implName: "litmus-parachain",
        specName: "litmus-parachain",
        specVersion: "9070",
        nativeToken: {
          id: "litmus-native-LIT",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.litmus-parachain.litentry.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2106,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "loom",
        sortIndex: 36,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Loom",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "loom-native-LOOM",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://kusama.dappchains.com",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2080,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "manta",
        sortIndex: 37,
        isTestnet: false,
        genesisHash: "0x7822fe86be209e140e1bdb80fb09539d1825e3d1dfee79ce37c336a832a26d48",
        prefix: 77,
        name: "Manta",
        chainName: "Manta Parachain",
        implName: "manta",
        specName: "manta",
        specVersion: "3090",
        nativeToken: {
          id: "manta-native-MANTA",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://pectinata.manta.systems",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2015,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "mars",
        sortIndex: 38,
        isTestnet: false,
        genesisHash: "0x1932f141fe67eba7ad0bdfe8292f0d932bf6ce4872433f707039de2794b9a18b",
        prefix: null,
        name: "Mars",
        chainName: "Mars",
        implName: "ares-mars",
        specName: "ares-mars",
        specVersion: "117",
        nativeToken: {
          id: "mars-native-AMAS",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://wss.mars.aresprotocol.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2008,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "moonbeam",
        sortIndex: 39,
        isTestnet: false,
        genesisHash: "0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d",
        prefix: 1284,
        name: "Moonbeam",
        chainName: "Moonbeam",
        implName: "moonbeam",
        specName: "moonbeam",
        specVersion: "1401",
        nativeToken: {
          id: "moonbeam-native-GLMR",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "secp256k1",
        subscanUrl: "https://moonbeam.subscan.io/",
        rpcs: [
          {
            url: "wss://wss.api.moonbeam.network",
            isHealthy: true,
          },
          {
            url: "wss://moonbeam.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://moonbeam-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: "https://moonbeam.moonscan.io/",
        ethereumRpcs: [
          {
            url: "https://rpc.api.moonbeam.network",
            isHealthy: true,
          },
          {
            url: "https://moonbeam.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "https://moonbeam-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumId: 1284,
        isHealthy: true,
        parathreads: [],
        paraId: 2004,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "moonriver",
        sortIndex: 40,
        isTestnet: false,
        genesisHash: "0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b",
        prefix: 1285,
        name: "Moonriver",
        chainName: "Moonriver",
        implName: "moonriver",
        specName: "moonriver",
        specVersion: "1502",
        nativeToken: {
          id: "moonriver-native-MOVR",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "secp256k1",
        subscanUrl: "https://moonriver.subscan.io/",
        rpcs: [
          {
            url: "wss://wss.moonriver.moonbeam.network",
            isHealthy: true,
          },
          {
            url: "wss://moonriver.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.pinknode.io/moonriver/explorer",
            isHealthy: true,
          },
          {
            url: "wss://moonriver-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: "https://moonriver.moonscan.io/",
        ethereumRpcs: [
          {
            url: "https://rpc.api.moonriver.moonbeam.network",
            isHealthy: true,
          },
          {
            url: "https://moonriver.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "https://moonriver-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumId: 1285,
        isHealthy: true,
        parathreads: [],
        paraId: 2023,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "nodle",
        sortIndex: 41,
        isTestnet: false,
        genesisHash: "0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21",
        prefix: 37,
        name: "Nodle",
        chainName: "Nodle Parachain",
        implName: "nodle-para",
        specName: "nodle-para",
        specVersion: "1",
        nativeToken: {
          id: "nodle-native-NODL",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://nodle.subscan.io/",
        rpcs: [
          {
            url: "wss://eden-rpc.dwellir.com",
            isHealthy: true,
          },
          {
            url: "wss://nodle-parachain.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.nodle.com",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2026,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "parallel",
        sortIndex: 42,
        isTestnet: false,
        genesisHash: "0xe61a41c53f5dcd0beb09df93b34402aada44cb05117b71059cce40a2723a4e97",
        prefix: 172,
        name: "Parallel",
        chainName: "Parallel",
        implName: "parallel",
        specName: "parallel",
        specVersion: "185",
        nativeToken: {
          id: "parallel-native-PARA",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://parallel.subscan.io/",
        rpcs: [
          {
            url: "wss://parallel.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.parallel.fi",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2012,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "parallel-heiko",
        sortIndex: 43,
        isTestnet: false,
        genesisHash: "0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b",
        prefix: 110,
        name: "Parallel Heiko",
        chainName: "Parallel Heiko",
        implName: "heiko",
        specName: "heiko",
        specVersion: "186",
        nativeToken: {
          id: "parallel-heiko-native-HKO",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://parallel-heiko.subscan.io/",
        rpcs: [
          {
            url: "wss://parallel-heiko.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://heiko-rpc.parallel.fi",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2085,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "phala",
        sortIndex: 44,
        isTestnet: false,
        genesisHash: "0x1bb969d85965e4bb5a651abbedf21a54b6b31a21f66b5401cc3f1e286268d736",
        prefix: 30,
        name: "Phala",
        chainName: "Phala",
        implName: "phala",
        specName: "phala",
        specVersion: "1090",
        nativeToken: {
          id: "phala-native-PHA",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://api.phala.network/ws",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2035,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "picasso",
        sortIndex: 45,
        isTestnet: false,
        genesisHash: "0x6811a339673c9daa897944dcdac99c6e2939cc88245ed21951a0a3c9a2be75bc",
        prefix: 49,
        name: "Picasso",
        chainName: "Picasso",
        implName: "picasso",
        specName: "picasso",
        specVersion: "1000",
        nativeToken: {
          id: "picasso-native-PICA",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://picasso-rpc.composable.finance",
            isHealthy: true,
          },
          {
            url: "wss://picasso-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2087,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "pichiu",
        sortIndex: 46,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Pichiu",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "pichiu-native-PCHU",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://kusama.kylin-node.co.uk",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2102,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "polkadex",
        sortIndex: 47,
        isTestnet: false,
        genesisHash: "0x3920bcb4960a1eef5580cd5367ff3f430eef052774f78468852f7b9cb39f8a3c",
        prefix: 88,
        name: "Polkadex",
        chainName: "Polkadex Main Network",
        implName: "polkadex-official",
        specName: "node",
        specVersion: "273",
        nativeToken: {
          id: "polkadex-native-PDEX",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://polkadex.subscan.io/",
        rpcs: [
          {
            url: "wss://mainnet.polkadex.trade/",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2040,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "polkasmith",
        sortIndex: 48,
        isTestnet: false,
        genesisHash: null,
        prefix: 98,
        name: "PolkaSmith",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "polkasmith-native-PKS",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://wss-polkasmith.polkafoundry.com",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2009,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "quartz",
        sortIndex: 49,
        isTestnet: false,
        genesisHash: "0xcd4d732201ebe5d6b014edda071c4203e16867305332301dc8d092044b28e554",
        prefix: 255,
        name: "Quartz",
        chainName: "QUARTZ by UNIQUE",
        implName: "quartz",
        specName: "quartz",
        specVersion: "921000",
        nativeToken: {
          id: "quartz-native-QTZ",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://quartz.subscan.io/",
        rpcs: [
          {
            url: "wss://quartz.unique.network",
            isHealthy: true,
          },
          {
            url: "wss://quartz.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://eu-ws-quartz.unique.network",
            isHealthy: true,
          },
          {
            url: "wss://us-ws-quartz.unique.network",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2095,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "robonomics",
        sortIndex: 50,
        isTestnet: false,
        genesisHash: "0x631ccc82a078481584041656af292834e1ae6daab61d2875b4dd0c14bb9b17bc",
        prefix: 32,
        name: "Robonomics",
        chainName: "Robonomics",
        implName: "robonomics-airalab",
        specName: "robonomics",
        specVersion: "16",
        nativeToken: {
          id: "robonomics-native-XRT",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://robonomics.subscan.io/",
        rpcs: [
          {
            url: "wss://kusama.rpc.robonomics.network/",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2048,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "sakura",
        sortIndex: 51,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "Sakura",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "sakura-native-SKU",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://sakura.subscan.io/",
        rpcs: [
          {
            url: "wss://api-sakura.clover.finance",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2016,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "sherpax",
        sortIndex: 52,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "SherpaX",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "sherpax-native-KSX",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://sherpax.chainx.org",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2013,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "shiden",
        sortIndex: 53,
        isTestnet: false,
        genesisHash: "0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108",
        prefix: 5,
        name: "Shiden",
        chainName: "Shiden",
        implName: "shiden",
        specName: "shiden",
        specVersion: "50",
        nativeToken: {
          id: "shiden-native-SDN",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://shiden.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.shiden.astar.network",
            isHealthy: true,
          },
          {
            url: "wss://shiden.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.pinknode.io/shiden/explorer",
            isHealthy: true,
          },
          {
            url: "wss://shiden-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: "https://blockscout.com/shiden",
        ethereumRpcs: [
          {
            url: "https://evm.shiden.astar.network",
            isHealthy: true,
          },
          {
            url: "https://shiden.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "https://shiden-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumId: 336,
        isHealthy: true,
        parathreads: [],
        paraId: 2007,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "sora-kusama",
        sortIndex: 54,
        isTestnet: false,
        genesisHash: "0x4f9366ee004d0b1b8f9834fc9cb41dc765eea1e6c15946b882450cd59713b7f3",
        prefix: null,
        name: "Sora Kusama",
        chainName: "SORA Kusama",
        implName: "sora_ksm",
        specName: "sora_ksm",
        specVersion: "1",
        nativeToken: {
          id: "sora-kusama-native-undefined",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://sora.subscan.io/",
        rpcs: [
          {
            url: "wss://ws.parachain-collator-1.c1.sora2.soramitsu.co.jp",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2011,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "statemine",
        sortIndex: 55,
        isTestnet: false,
        genesisHash: "0x48239ef607d7928874027a43a67689209727dfb3d3dc5e5b03a39bdc2eda771a",
        prefix: 2,
        name: "Statemine",
        chainName: "Statemine",
        implName: "statemine",
        specName: "statemine",
        specVersion: "900",
        nativeToken: {
          id: "statemine-native-KSM",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://statemine.subscan.io/",
        rpcs: [
          {
            url: "wss://statemine-rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://statemine.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://statemine-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 1000,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "statemint",
        sortIndex: 56,
        isTestnet: false,
        genesisHash: "0x68d56f15f85d3136970ec16946040bc1752654e906147f7e43e9d539d7c3de2f",
        prefix: null,
        name: "Statemint",
        chainName: "Statemint",
        implName: "statemint",
        specName: "statemint",
        specVersion: "900",
        nativeToken: {
          id: "statemint-native-DOT",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://statemint-rpc.polkadot.io",
            isHealthy: true,
          },
          {
            url: "wss://statemint.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://statemint-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 1000,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "subdao",
        sortIndex: 57,
        isTestnet: false,
        genesisHash: null,
        prefix: null,
        name: "SubDAO",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "subdao-native-GOV",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://parachain-rpc.subdao.org",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2018,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "subgame",
        sortIndex: 58,
        isTestnet: false,
        genesisHash: "0x01cf4dbc973387c70f4db8fad8551f71faf191d9f08044d37fc617b30ffae8b9",
        prefix: 27,
        name: "SubGame",
        chainName: "SubGame",
        implName: "subgame",
        specName: "subgame",
        specVersion: "174",
        nativeToken: {
          id: "subgame-native-SGB",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://subgame.subscan.io/",
        rpcs: [
          {
            url: "wss://mainnet.subgame.org/",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2017,
        relay: {
          id: "polkadot",
        },
      },
      {
        id: "subgame-gamma",
        sortIndex: 59,
        isTestnet: false,
        genesisHash: "0x6584d9fcd3c350fd2b17e0118547c1ea54960b925d6c3255a78ac77aeeca9d04",
        prefix: 27,
        name: "SubGame Gamma",
        chainName: "Subgame Gamma",
        implName: "subgame",
        specName: "subgame",
        specVersion: "1",
        nativeToken: {
          id: "subgame-gamma-native-GSGB",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://gamma.subgame.org/",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2018,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "subsocial",
        sortIndex: 60,
        isTestnet: false,
        genesisHash: "0x0bd72c1c305172e1275278aaeb3f161e02eccb7a819e63f62d47bd53a28189f8",
        prefix: 28,
        name: "Subsocial",
        chainName: "Subsocial",
        implName: "dappforce-subsocial",
        specName: "subsocial",
        specVersion: "18",
        nativeToken: {
          id: "subsocial-native-SUB",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.subsocial.network",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "subsocialx",
        sortIndex: 61,
        isTestnet: false,
        genesisHash: null,
        prefix: 28,
        name: "SubsocialX",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "subsocialx-native-SUB",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://para.subsocial.network",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: 2100,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "turing",
        sortIndex: 62,
        isTestnet: false,
        genesisHash: "0x0f62b701fb12d02237a33b84818c11f621653d2b1614c777973babf4652b535d",
        prefix: 51,
        name: "Turing",
        chainName: "Turing Network",
        implName: "turing",
        specName: "turing",
        specVersion: "280",
        nativeToken: {
          id: "turing-native-TUR",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.turing.oak.tech",
            isHealthy: true,
          },
          {
            url: "wss://turing.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2114,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "unorthodox",
        sortIndex: 63,
        isTestnet: false,
        genesisHash: "0xb0f86ecc2d65b9a8a01d88d3f9b808a7e9902d418951fdb9588880cf8e821af1",
        prefix: 42,
        name: "Unorthodox",
        chainName: "Standard Kusama Parachain",
        implName: "standard10",
        specName: "standard",
        specVersion: "9090",
        nativeToken: {
          id: "unorthodox-native-STND",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc.kusama.standard.tech",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2094,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "zeitgeist",
        sortIndex: 64,
        isTestnet: false,
        genesisHash: "0x1bf2a2ecb4a868de66ea8610f2ce7c8c43706561b6476031315f6640fe38e060",
        prefix: 73,
        name: "Zeitgeist",
        chainName: "Zeitgeist",
        implName: "zeitgeist",
        specName: "zeitgeist",
        specVersion: "35",
        nativeToken: {
          id: "zeitgeist-native-ZTG",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://rpc-0.zeitgeist.pm",
            isHealthy: true,
          },
          {
            url: "wss://zeitgeist-rpc.dwellir.com",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: 2101,
        relay: {
          id: "kusama",
        },
      },
      {
        id: "dolphin",
        sortIndex: 65,
        isTestnet: true,
        genesisHash: null,
        prefix: 42,
        name: "Dolphin Testnet",
        chainName: null,
        implName: null,
        specName: null,
        specVersion: null,
        nativeToken: {
          id: "dolphin-native-DOL",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://dolphin.subscan.io/",
        rpcs: [
          {
            url: "wss://trillian.dolphin.red/",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "mandala",
        sortIndex: 66,
        isTestnet: true,
        genesisHash: "0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b",
        prefix: 42,
        name: "Mandala",
        chainName: "Acala Mandala TC7",
        implName: "mandala",
        specName: "mandala",
        specVersion: "2050",
        nativeToken: {
          id: "mandala-native-ACA",
        },
        tokensCurrencyIdIndex: 0,
        tokens: [
          {
            id: "mandala-orml-ACA",
          },
          {
            id: "mandala-orml-AUSD",
          },
          {
            id: "mandala-orml-DOT",
          },
          {
            id: "mandala-orml-LDOT",
          },
          {
            id: "mandala-orml-RENBTC",
          },
          {
            id: "mandala-orml-CASH",
          },
          {
            id: "mandala-orml-KAR",
          },
          {
            id: "mandala-orml-KUSD",
          },
          {
            id: "mandala-orml-KSM",
          },
          {
            id: "mandala-orml-LKSM",
          },
          {
            id: "mandala-orml-TAI",
          },
          {
            id: "mandala-orml-BNC",
          },
          {
            id: "mandala-orml-VSKSM",
          },
          {
            id: "mandala-orml-PHA",
          },
          {
            id: "mandala-orml-KINT",
          },
          {
            id: "mandala-orml-KBTC",
          },
        ],
        account: "*25519",
        subscanUrl: "https://acala-testnet.subscan.io/",
        rpcs: [
          {
            url: "wss://mandala.polkawallet.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [
          {
            url: "https://tc7-eth.aca-dev.network",
            isHealthy: true,
          },
        ],
        ethereumId: 595,
        isHealthy: true,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "mangata-testnet",
        sortIndex: 67,
        isTestnet: true,
        genesisHash: "0x8032ad7a75a2b9732315592c672ec6d0ddf95308de03a19878ed8627ae8796cc",
        prefix: 42,
        name: "Mangata Testnet",
        chainName: "Mangata Public Testnet",
        implName: "mangata-parachain",
        specName: "mangata-parachain",
        specVersion: "1",
        nativeToken: {
          id: "mangata-testnet-native-MGAT",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://v4-prod-collator-01.mangatafinance.cloud",
            isHealthy: false,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: false,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "moonbase",
        sortIndex: 68,
        isTestnet: true,
        genesisHash: "0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527",
        prefix: 1287,
        name: "Moonbase Alpha",
        chainName: "Moonbase Alpha",
        implName: "moonbase",
        specName: "moonbase",
        specVersion: "1502",
        nativeToken: {
          id: "moonbase-native-DEV",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "secp256k1",
        subscanUrl: "https://moonbase.subscan.io/",
        rpcs: [
          {
            url: "wss://moonbeam-alpha.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: "https://moonbase.moonscan.io/",
        ethereumRpcs: [
          {
            url: "https://rpc.api.moonbase.moonbeam.network",
            isHealthy: true,
          },
          {
            url: "https://moonbeam-alpha.api.onfinality.io/public-ws",
            isHealthy: true,
          },
        ],
        ethereumId: 1287,
        isHealthy: true,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "neumann",
        sortIndex: 69,
        isTestnet: true,
        genesisHash: "0x42e75532d6809775cef4b9ca8e4bb49be2dc1e87c9ff1ba299e78481b5cb3047",
        prefix: 51,
        name: "Neumann",
        chainName: "Neumann Network",
        implName: "neumann",
        specName: "neumann",
        specVersion: "280",
        nativeToken: {
          id: "neumann-native-NEU",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://neumann.api.onfinality.io/public-ws",
            isHealthy: true,
          },
          {
            url: "wss://rpc.testnet.oak.tech",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "shibuya",
        sortIndex: 70,
        isTestnet: true,
        genesisHash: "0xddb89973361a170839f80f152d2e9e38a376a5a7eccefcade763f46a8e567019",
        prefix: 5,
        name: "Shibuya Testnet",
        chainName: "Shibuya Testnet",
        implName: "shibuya",
        specName: "shibuya",
        specVersion: "49",
        nativeToken: {
          id: "shibuya-native-SBY",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://shibuya.subscan.io/",
        rpcs: [
          {
            url: "wss://rpc.shibuya.astar.network",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: "https://blockscout.com/shibuya",
        ethereumRpcs: [
          {
            url: "https://evm.shibuya.astar.network",
            isHealthy: true,
          },
        ],
        ethereumId: 81,
        isHealthy: true,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "westend",
        sortIndex: 71,
        isTestnet: true,
        genesisHash: "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e",
        prefix: 42,
        name: "Westend",
        chainName: "Westend",
        implName: "parity-westend",
        specName: "westend",
        specVersion: "9220",
        nativeToken: {
          id: "westend-native-WND",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: "https://westend.subscan.io/",
        rpcs: [
          {
            url: "wss://westend-rpc.polkadot.io",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: null,
        relay: null,
      },
      {
        id: "zero-io",
        sortIndex: 72,
        isTestnet: true,
        genesisHash: "0xa2a5f57ee48effcf4d09e247e1fa58080166d02cd6078a0206484bf3ac52b311",
        prefix: 25,
        name: "Zero.io",
        chainName: "ZERO.IO",
        implName: "alphaville",
        specName: "subzero",
        specVersion: "50",
        nativeToken: {
          id: "zero-io-native-ZERO",
        },
        tokensCurrencyIdIndex: null,
        tokens: null,
        account: "*25519",
        subscanUrl: null,
        rpcs: [
          {
            url: "wss://alphaville.zero.io/",
            isHealthy: true,
          },
        ],
        ethereumExplorerUrl: null,
        ethereumRpcs: [],
        ethereumId: null,
        isHealthy: true,
        parathreads: [],
        paraId: null,
        relay: null,
      },
    ],
  },
}

export const getChainData = jest.fn(() => Promise.resolve(data.data))
