import fs from "fs"
import path from "path"

import { fetchChains, fetchEvmNetworks, fetchTokens } from "../src/graphql"

async function generateMockData() {
  fs.writeFileSync(
    path.resolve(__dirname, "../src/__mocks__/_mockData.ts"),
    `// This file is generated by a script,
// update it by running the following command:
// yarn workspace @talismn/chaindata-provider-extension generate-mock-data

export const mockChainsResponse = ${JSON.stringify(await fetchChains(), null, 2)}

export const mockEvmNetworksResponse = ${JSON.stringify(await fetchEvmNetworks(), null, 2)}

export const mockTokensResponse = ${JSON.stringify(await fetchTokens(), null, 2)}
`
  )
}

// Use this command to run this file:
//
// ```
// yarn workspace @talismn/chaindata-provider-extension generate-mock-data
// ```
generateMockData()
