import type { Chain, EvmNetwork, Token } from "../types"
import { chains as initChains } from "./chains"
import { evmNetworks as initEvmNetworks } from "./evm-networks"
import { miniMetadatas as initMiniMetadatas } from "./mini-metadatas"
import { tokens as initSubstrateTokens } from "./tokens"

// The init files imported in this module are generated by a script.
//
// They are used in two places:
// 1. As fallbacks for fresh installations who are unable to pull an initial set of data from the upstream chaindata repo.
// 2. As mock data for tests.
//
// They should be periodically updated with the latest state of chaindata.
// You can update them by running the following command:
// `pnpm chore:generate-init-data`

export const fetchInitChains = async (): Promise<Chain[]> =>
  // `as unknown` is needed for when we make breaking changes to chaindata.
  // when this happens, we don't want tsc to check this type, because that would prevent us from compiling
  // the generateInitData script, which in turn updates the initChains data to match the new changes
  initChains as unknown as Chain[]
export const fetchInitEvmNetworks = async (): Promise<EvmNetwork[]> =>
  // `as unknown` is needed for when we make breaking changes to chaindata.
  // when this happens, we don't want tsc to check this type, because that would prevent us from compiling
  // the generateInitData script, which in turn updates the initEvmNetworks data to match the new changes
  initEvmNetworks as unknown as EvmNetwork[]
export const fetchInitSubstrateTokens = async (): Promise<Token[]> =>
  // `as unknown` is needed for when we make breaking changes to chaindata.
  // when this happens, we don't want tsc to check this type, because that would prevent us from compiling
  // the generateInitData script, which in turn updates the initSubstrateTokens data to match the new changes
  initSubstrateTokens as unknown as Token[]

// TODO: Move `fetchMiniMetadatas` into `@talismn/balances`,
// so that we don't have a circular import between `@talismn/balances` and `@talismn/chaindata-provider`.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const fetchInitMiniMetadatas = async (): Promise<any[]> => initMiniMetadatas
