import type { MiniMetadata } from "@talismn/balances"
import type { Chain, EvmNetwork, Token } from "@talismn/chaindata-provider"

// The init files imported in this module are generated by a script.
//
// They are used in two places:
// 1. As fallbacks for fresh installations who are unable to pull an initial set of data from the upstream chaindata repo.
// 2. As mock data for tests.
//
// They should be periodically updated with the latest state of chaindata.
// You can update them by running the following command:
// `yarn workspace @talismn/chaindata-provider generate-init-data`

export const fetchInitChains = async (): Promise<Chain[]> =>
  (await import(/* webpackChunkName: "talisman-init-data-chains" */ "./chains")).chains as Chain[]
export const fetchInitEvmNetworks = async (): Promise<EvmNetwork[]> =>
  (await import(/* webpackChunkName: "talisman-init-data-evm-networks" */ "./evm-networks"))
    .evmNetworks
export const fetchInitTokens = async (): Promise<Token[]> =>
  (await import(/* webpackChunkName: "talisman-init-data-tokens" */ "./tokens")).tokens as Token[]
export const fetchInitMiniMetadatas = async (): Promise<MiniMetadata[]> =>
  (await import(/* webpackChunkName: "talisman-init-data-mini-metadatas" */ "./mini-metadatas"))
    .miniMetadatas as MiniMetadata[]
