export const tokens = [
  {
    id: "kusama-asset-hub-substrate-assets-16-aris",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "ARIS",
    decimals: 8,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/aris.svg",
    existentialDeposit: "10000000",
    assetId: "16",
    isFrozen: false,
    chain: {
      id: "kusama-asset-hub",
    },
  },
  {
    id: "kusama-asset-hub-substrate-assets-1984-usdt",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "USDT",
    decimals: 6,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/usdt.svg",
    existentialDeposit: "100",
    assetId: "1984",
    isFrozen: false,
    chain: {
      id: "kusama-asset-hub",
    },
    coingeckoId: "tether",
  },
  {
    id: "kusama-asset-hub-substrate-assets-8-rmrk",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "RMRK",
    decimals: 10,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/rmrk.svg",
    existentialDeposit: "10000",
    assetId: "8",
    isFrozen: false,
    chain: {
      id: "kusama-asset-hub",
    },
    coingeckoId: "rmrk",
  },
  {
    id: "kusama-asset-hub-substrate-native",
    type: "substrate-native",
    isTestnet: false,
    isDefault: true,
    symbol: "KSM",
    decimals: 12,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/ksm.svg",
    existentialDeposit: "3333333",
    chain: {
      id: "kusama-asset-hub",
    },
    coingeckoId: "kusama",
  },
  {
    id: "kusama-bridge-hub-substrate-native",
    type: "substrate-native",
    isTestnet: false,
    isDefault: true,
    symbol: "KSM",
    decimals: 12,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/chains/kusama-bridge-hub.svg",
    existentialDeposit: "33333333",
    chain: {
      id: "kusama-bridge-hub",
    },
  },
  {
    id: "kusama-substrate-native",
    type: "substrate-native",
    isTestnet: false,
    isDefault: true,
    symbol: "KSM",
    decimals: 12,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/ksm.svg",
    existentialDeposit: "333333333",
    chain: {
      id: "kusama",
    },
    coingeckoId: "kusama",
  },
  {
    id: "polkadot-asset-hub-substrate-assets-1337-usdc",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "USDC",
    decimals: 6,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/coingecko/usd-coin.webp",
    existentialDeposit: "70000",
    assetId: "1337",
    isFrozen: false,
    chain: {
      id: "polkadot-asset-hub",
    },
    coingeckoId: "usd-coin",
  },
  {
    id: "polkadot-asset-hub-substrate-assets-17-wifd",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "WIFD",
    decimals: 10,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/wifd.svg",
    existentialDeposit: "1",
    assetId: "17",
    isFrozen: false,
    chain: {
      id: "polkadot-asset-hub",
    },
  },
  {
    id: "polkadot-asset-hub-substrate-assets-1984-usdt",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "USDT",
    decimals: 6,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/usdt.svg",
    existentialDeposit: "70000",
    assetId: "1984",
    isFrozen: false,
    chain: {
      id: "polkadot-asset-hub",
    },
    coingeckoId: "tether",
  },
  {
    id: "polkadot-asset-hub-substrate-assets-23-pink",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "PINK",
    decimals: 10,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/pink.png",
    existentialDeposit: "1",
    assetId: "23",
    isFrozen: false,
    chain: {
      id: "polkadot-asset-hub",
    },
  },
  {
    id: "polkadot-asset-hub-substrate-assets-30-ded",
    type: "substrate-assets",
    isTestnet: false,
    isDefault: true,
    symbol: "DED",
    decimals: 10,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/ded.svg",
    existentialDeposit: "1",
    assetId: "30",
    isFrozen: false,
    chain: {
      id: "polkadot-asset-hub",
    },
    coingeckoId: "dot-is-ded",
  },
  {
    id: "polkadot-asset-hub-substrate-native",
    type: "substrate-native",
    isTestnet: false,
    isDefault: true,
    symbol: "DOT",
    decimals: 10,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/dot.svg",
    existentialDeposit: "100000000",
    chain: {
      id: "polkadot-asset-hub",
    },
    coingeckoId: "polkadot",
  },
  {
    id: "polkadot-bridge-hub-substrate-native",
    type: "substrate-native",
    isTestnet: false,
    isDefault: true,
    symbol: "DOT",
    decimals: 10,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/chains/polkadot-bridge-hub.svg",
    existentialDeposit: "1000000000",
    chain: {
      id: "polkadot-bridge-hub",
    },
  },
  {
    id: "polkadot-substrate-native",
    type: "substrate-native",
    isTestnet: false,
    isDefault: true,
    symbol: "DOT",
    decimals: 10,
    logo: "https://raw.githubusercontent.com/TalismanSociety/chaindata/main/assets/tokens/dot.svg",
    existentialDeposit: "10000000000",
    chain: {
      id: "polkadot",
    },
    coingeckoId: "polkadot",
    dcentName: "POLKADOT",
  },
]
