import { MiniMetadata } from "@talismn/balances"
import { Chain, EvmNetwork, Token } from "@talismn/chaindata-provider"

// These json files are generated by a script.
// Update them by running the following command:
// yarn workspace @talismn/chaindata-provider-extension generate-init-data
import initChainsResponse from "./chains.json"
import initEvmNetworksResponse from "./evm-networks.json"
import initMiniMetadatasResponse from "./mini-metadatas.json"
import initTokensResponse from "./tokens.json"

export const fetchInitChains = async () => initChainsResponse as Chain[]
export const fetchInitEvmNetworks = async () => initEvmNetworksResponse as EvmNetwork[]
export const fetchInitTokens = async () => initTokensResponse as Token[]
export const fetchInitMiniMetadatas = async () => initMiniMetadatasResponse as MiniMetadata[]
