// These json files are generated by a script.
// Update them by running the following command:
// yarn workspace @talismn/chaindata-provider-extension generate-init-data
import initChainsResponse from "./chains.json"
import initEvmNetworksResponse from "./evm-networks.json"

// TODO remove the .map() after fixing init data
export const fetchInitChains = async () =>
  initChainsResponse.map((n) => ({
    ...n,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    isDefault: (n as any).isDefault === undefined ? true : (n as any).isDefault,
  }))

// TODO remove the .map() after fixing init data
export const fetchInitEvmNetworks = async () =>
  initEvmNetworksResponse.map((n) => ({
    ...n,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    isDefault: (n as any).isDefault === undefined ? true : (n as any).isDefault,
  }))
