import { MiniMetadata } from "@talismn/balances"
import { Chain, EvmNetwork, Token } from "@talismn/chaindata-provider"

// These init files are generated by a script.
// Update them by running the following command:
// yarn workspace @talismn/chaindata-provider-extension generate-init-data
import { chains as initChainsResponse } from "./chains"
import { evmNetworks as initEvmNetworksResponse } from "./evm-networks"
import { miniMetadatas as initMiniMetadatasResponse } from "./mini-metadatas"
import { tokens as initTokensResponse } from "./tokens"

export const fetchInitChains = async (): Promise<Chain[]> => initChainsResponse
export const fetchInitEvmNetworks = async (): Promise<EvmNetwork[]> => initEvmNetworksResponse
export const fetchInitTokens = async (): Promise<Token[]> => initTokensResponse as Token[]
export const fetchInitMiniMetadatas = async (): Promise<MiniMetadata[]> =>
  initMiniMetadatasResponse as MiniMetadata[]
