export { ReactComponent as EthereumCircleBorderedLogo } from "./ethereum-circle-bordered.svg"
export { ReactComponent as EthereumCircleLogo } from "./ethereum-circle.svg"
export { ReactComponent as HandMonoLogo } from "./logo-hand-mono.svg"
export { ReactComponent as HandMonoSilhouetteLogo } from "./logo-hand-mono-silhouette.svg"
export { ReactComponent as PolkadotCircleBorderedLogo } from "./polkadot-circle-bordered.svg"
export { ReactComponent as PolkadotCircleLogo } from "./polkadot-circle.svg"
export { ReactComponent as TalismanWhiteLogo } from "./talisman-white.svg"
export { ReactComponent as TalismanWhiteVerticalLogo } from "./talisman-white-vertical.svg"
