export { ReactComponent as FullColorSmallLogo } from "./talisman-full-color-small.svg"
export { ReactComponent as FullColorLogo } from "./talisman-full-color.svg"
export { ReactComponent as FullColorVerticalLogo } from "./talisman-full-color-vertical.svg"
export { ReactComponent as HandColorLogo } from "./logo-hand-color.svg"
export { ReactComponent as HandMonoLogo } from "./logo-hand-mono.svg"
export { ReactComponent as PolkadotCircleLogo } from "./polkadot-circle.svg"
export { ReactComponent as EthereumCircleLogo } from "./ethereum-circle.svg"
