/**
 * Initial seed for the MetaMask phishing detector.
 *
 * Why a seed file at all?
 * The runtime fetches the live blocklist from MetaMask's phishing API the first
 * time `isPhishingSite` is called when no IndexedDB cache exists
 * (and again every 5 minutes). If that first refresh fails, this seed provides
 * minimal fallback coverage until the next refresh.
 *
 * Source / license
 * Data sampled from `https://phishing-detection.api.cx.metamask.io/v1/stalelist`,
 * served by `@metamask/phishing-controller` (MIT). Domain blocklists are factual
 * data and not subject to copyright.
 *
 * Sampling strategy
 * Full allowlist + full fuzzylist (both small) are inlined verbatim. The
 * blocklist is sampled at a regular stride across the alphabet so the seed
 * covers a diverse cross-section of phishing patterns rather than a single
 * cluster. The full ~240k-entry blocklist arrives via the periodic refresh.
 */

import type { MetaMaskPhishingList } from "./ParaverseProtector"

export const initialPhishingList: MetaMaskPhishingList = {
  allowlist: [
    "127.0.0.1",
    "consensys.info",
    "cryptofitties.com",
    "cryptokitties.co",
    "cryptotitties.fun",
    "etcerscan.com",
    "etherscan.com",
    "etherscan.io",
    "example.walletconnect.org",
    "launchpad.ethereum.org",
    "localhost",
    "magic.link",
    "magiceden.us",
    "makerfoundation.com",
    "metacask.com",
    "metacask.io",
    "metamark.lt",
    "metamask.io",
    "metatask.io",
    "metmask.com",
    "monadbridge.com",
    "myetherwallet.com",
    "opengea.org",
    "opensea.com",
    "opensea.foundation",
    "opensea.gr",
    "opensea.institute",
    "opensea.io",
    "opensea.pro",
    "opensea.ru",
    "openseal.ch",
    "openseam.co",
    "openseas.gr",
    "opensee.io",
    "openset.co",
    "openspa.info",
    "pcswap.org",
    "phosphor.xyz",
    "relay.walletconnect.org",
    "reown.com",
    "reown.org",
    "revoke.cash",
    "satoshilabs.com",
    "satoshilabs.design",
    "secure.walletconnect.org",
    "sophon.xyz",
    "storage.googleapis.com",
    "walletconnect.com",
    "walletconnect.foundation",
    "walletconnect.network",
    "walletconnect.org",
    "web3inbox.com",
    "web3inbox.org",
    "web3modal.com",
    "web3modal.org",
    "talisman.xyz",
  ],
  blocklist: [
    "*.chrom-coinbse-extenson.pages.dev",
    "1inch.getairdrop.net",
    "485790coinbase.com",
    "874962coinbase.com",
    "accessopenseamints8.vercel.app",
    "airdrop-0xscniciabs.xyz",
    "allocate-lions.org",
    "api-aa.sjc.c9oinbase.ws",
    "app-wallet.online",
    "arbitrum.co.uk",
    "auth-cbase-xtnsnn.gitbook.io",
    "balancefunverify.com",
    "bestwallettokens.net",
    "blsfw.top",
    "build.assiterr.network",
    "cbrbpipo.workers.dev",
    "checker-rainbow.xyz",
    "claim-scroll.fun",
    "claimsolana.world",
    "coinbacechrome-extension.typedream.app",
    "coinbase-scan.com",
    "coinbasegive.cc",
    "coinbesexxtennisn.webflow.io",
    "com-app.cfd",
    "connect-coinbase-exts-cdn-autth-cdn.webflow.io",
    "cripto-coinbase-extn.typedream.app",
    "dango-token.xyz",
    "decentralizedsystem.world",
    "dexsync-node.xyz",
    "download-easily-rabby-wallet-9hl.pages.dev",
    "eigen-layr.net",
    "en-us-coinpro-learn.typedream.app",
    "etherfi-foundation.pages.dev",
    "exodeus-us-web.pages.dev",
    "faq-dydx-trade-en-us.pages.dev",
    "fixnodedapp.com",
    "fun-livestream.live",
    "ghvaults.eu.com",
    "gruiqsqf.workers.dev",
    "help-en-io-metamask.teachable.com",
    "home-coinbase-walt.pages.dev",
    "hyperliquid.com-beta-secure-app-dex.pro",
    "intellax.io.api-cloudflare.com",
    "kakaospeaks.com",
    "kra42cc-cc.ru",
    "kraken-security.webflow.io",
    "kryptonix.business",
    "legalnotice-x.com",
    "live-babylonlabs.com",
    "ltc-sushi.lat",
    "mantr.space",
    "memedoge.site",
    "metamask-login.typedream.app",
    "metamaskteam.webflow.io",
    "metemask.me",
    "mmpns.pages.dev",
    "mremvnom.workers.dev",
    "myxkon.com",
    "niiiion.live",
    "ohwg2vj5.workers.dev",
    "opensea-mystery-nft037.vercel.app",
    "owllto.us",
    "pengupenguins.xyz",
    "phantomware.pages.dev",
    "polkadot2.xyz",
    "portalbridge.net",
    "proposal-zerolend.app",
    "pythnetworks.pages.dev",
    "railguns.pages.dev",
    "register-omaleytoken.xyz",
    "reward-virtuals.com",
    "scr.beefyapps.sbs",
    "send-suilend.fi",
    "slushupdate.info",
    "solproweb.xyz",
    "sso-coinbase-coms-cdn-t-auth.typedream.app",
    "start-unlockings-blockpage.top",
    "suite.web3apps.live",
    "swapx-x.fi",
    "testnet-soniclab.com",
    "tonkeper-walet-extension.webflow.io",
    "trump.hrwlq.icu",
    "uniswap--exchange-uniswap.webflow.io",
    "urushrwd.workers.dev",
    "usz00mcom2j7gp6h.icu",
    "vedcckvp.workers.dev",
    "votes-venus.xyz",
    "wallet-reward.xyz",
    "web-extra.fi",
    "welcome-metamaskhelps----docs.typedream.app",
    "worldlibertyforum-vote.com",
    "www-uphoild-wallets.pro",
    "xn--moonshtt-osb.net",
    "yourgift.top",
    "zkdx-nft.pages.dev",
  ],
  blocklistPaths: [],
  fuzzylist: [
    "cryptokitties.co",
    "etherscan.io",
    "launchpad.ethereum.org",
    "makerfoundation.com",
    "metamask.io",
    "myetherwallet.com",
    "opensea.io",
    "satoshilabs.com",
  ],
  tolerance: 1,
  version: 2,
}
