export const MYSTICAL_PHYSICS = {
  blur: 100,
  sizeArtifact: 3,
  sizeTracker: 1,
  minOpacityArtifact: 0,
  minOpacityAcolyte: 0.15,
  maxOpacityArtifact: 0.15,
  maxOpacityAcolyte: 0.4,
  stiffnessArtifact: 500,
  stiffnessAcolyte: 500,
  easeArtifact: "easeInOut",
  easeAcolyte: "easeOut",
  durationArtifact: 8,
  durationAcolyte: 6,
}
