name: Playwright Tests
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update & Enable corepack
      run: npm install -g corepack@latest && corepack enable
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Build papi descriptors
      run: pnpm papi
    - name: Build the Wallet
      run: pnpm run build:extension
    - name: Install Playwright Browser - Chromium
      run: pnpm exec playwright install --with-deps chromium
    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb
    - name: Run Playwright tests with Xvfb
      run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" \
          pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
